// Code generated by ent, DO NOT EDIT.

package conversationmember

import (
	"social-server/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldLTE(FieldID, id))
}

// ConversationID applies equality check predicate on the "conversation_id" field. It's identical to ConversationIDEQ.
func ConversationID(v uuid.UUID) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldEQ(FieldConversationID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldEQ(FieldUserID, v))
}

// JoinedAt applies equality check predicate on the "joined_at" field. It's identical to JoinedAtEQ.
func JoinedAt(v time.Time) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldEQ(FieldJoinedAt, v))
}

// LastReadAt applies equality check predicate on the "last_read_at" field. It's identical to LastReadAtEQ.
func LastReadAt(v time.Time) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldEQ(FieldLastReadAt, v))
}

// ConversationIDEQ applies the EQ predicate on the "conversation_id" field.
func ConversationIDEQ(v uuid.UUID) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldEQ(FieldConversationID, v))
}

// ConversationIDNEQ applies the NEQ predicate on the "conversation_id" field.
func ConversationIDNEQ(v uuid.UUID) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldNEQ(FieldConversationID, v))
}

// ConversationIDIn applies the In predicate on the "conversation_id" field.
func ConversationIDIn(vs ...uuid.UUID) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldIn(FieldConversationID, vs...))
}

// ConversationIDNotIn applies the NotIn predicate on the "conversation_id" field.
func ConversationIDNotIn(vs ...uuid.UUID) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldNotIn(FieldConversationID, vs...))
}

// ConversationIDGT applies the GT predicate on the "conversation_id" field.
func ConversationIDGT(v uuid.UUID) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldGT(FieldConversationID, v))
}

// ConversationIDGTE applies the GTE predicate on the "conversation_id" field.
func ConversationIDGTE(v uuid.UUID) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldGTE(FieldConversationID, v))
}

// ConversationIDLT applies the LT predicate on the "conversation_id" field.
func ConversationIDLT(v uuid.UUID) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldLT(FieldConversationID, v))
}

// ConversationIDLTE applies the LTE predicate on the "conversation_id" field.
func ConversationIDLTE(v uuid.UUID) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldLTE(FieldConversationID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldLTE(FieldUserID, v))
}

// JoinedAtEQ applies the EQ predicate on the "joined_at" field.
func JoinedAtEQ(v time.Time) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldEQ(FieldJoinedAt, v))
}

// JoinedAtNEQ applies the NEQ predicate on the "joined_at" field.
func JoinedAtNEQ(v time.Time) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldNEQ(FieldJoinedAt, v))
}

// JoinedAtIn applies the In predicate on the "joined_at" field.
func JoinedAtIn(vs ...time.Time) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldIn(FieldJoinedAt, vs...))
}

// JoinedAtNotIn applies the NotIn predicate on the "joined_at" field.
func JoinedAtNotIn(vs ...time.Time) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldNotIn(FieldJoinedAt, vs...))
}

// JoinedAtGT applies the GT predicate on the "joined_at" field.
func JoinedAtGT(v time.Time) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldGT(FieldJoinedAt, v))
}

// JoinedAtGTE applies the GTE predicate on the "joined_at" field.
func JoinedAtGTE(v time.Time) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldGTE(FieldJoinedAt, v))
}

// JoinedAtLT applies the LT predicate on the "joined_at" field.
func JoinedAtLT(v time.Time) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldLT(FieldJoinedAt, v))
}

// JoinedAtLTE applies the LTE predicate on the "joined_at" field.
func JoinedAtLTE(v time.Time) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldLTE(FieldJoinedAt, v))
}

// LastReadAtEQ applies the EQ predicate on the "last_read_at" field.
func LastReadAtEQ(v time.Time) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldEQ(FieldLastReadAt, v))
}

// LastReadAtNEQ applies the NEQ predicate on the "last_read_at" field.
func LastReadAtNEQ(v time.Time) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldNEQ(FieldLastReadAt, v))
}

// LastReadAtIn applies the In predicate on the "last_read_at" field.
func LastReadAtIn(vs ...time.Time) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldIn(FieldLastReadAt, vs...))
}

// LastReadAtNotIn applies the NotIn predicate on the "last_read_at" field.
func LastReadAtNotIn(vs ...time.Time) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldNotIn(FieldLastReadAt, vs...))
}

// LastReadAtGT applies the GT predicate on the "last_read_at" field.
func LastReadAtGT(v time.Time) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldGT(FieldLastReadAt, v))
}

// LastReadAtGTE applies the GTE predicate on the "last_read_at" field.
func LastReadAtGTE(v time.Time) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldGTE(FieldLastReadAt, v))
}

// LastReadAtLT applies the LT predicate on the "last_read_at" field.
func LastReadAtLT(v time.Time) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldLT(FieldLastReadAt, v))
}

// LastReadAtLTE applies the LTE predicate on the "last_read_at" field.
func LastReadAtLTE(v time.Time) predicate.ConversationMember {
	return predicate.ConversationMember(sql.FieldLTE(FieldLastReadAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ConversationMember) predicate.ConversationMember {
	return predicate.ConversationMember(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ConversationMember) predicate.ConversationMember {
	return predicate.ConversationMember(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ConversationMember) predicate.ConversationMember {
	return predicate.ConversationMember(sql.NotPredicates(p))
}
