// Code generated by ent, DO NOT EDIT.

package postmedia

import (
	"social-server/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLTE(FieldID, id))
}

// PostID applies equality check predicate on the "post_id" field. It's identical to PostIDEQ.
func PostID(v uuid.UUID) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldPostID, v))
}

// MediaAssetID applies equality check predicate on the "media_asset_id" field. It's identical to MediaAssetIDEQ.
func MediaAssetID(v uuid.UUID) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldMediaAssetID, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldCreatedAt, v))
}

// PostIDEQ applies the EQ predicate on the "post_id" field.
func PostIDEQ(v uuid.UUID) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldPostID, v))
}

// PostIDNEQ applies the NEQ predicate on the "post_id" field.
func PostIDNEQ(v uuid.UUID) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNEQ(FieldPostID, v))
}

// PostIDIn applies the In predicate on the "post_id" field.
func PostIDIn(vs ...uuid.UUID) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldIn(FieldPostID, vs...))
}

// PostIDNotIn applies the NotIn predicate on the "post_id" field.
func PostIDNotIn(vs ...uuid.UUID) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNotIn(FieldPostID, vs...))
}

// PostIDGT applies the GT predicate on the "post_id" field.
func PostIDGT(v uuid.UUID) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGT(FieldPostID, v))
}

// PostIDGTE applies the GTE predicate on the "post_id" field.
func PostIDGTE(v uuid.UUID) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGTE(FieldPostID, v))
}

// PostIDLT applies the LT predicate on the "post_id" field.
func PostIDLT(v uuid.UUID) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLT(FieldPostID, v))
}

// PostIDLTE applies the LTE predicate on the "post_id" field.
func PostIDLTE(v uuid.UUID) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLTE(FieldPostID, v))
}

// MediaAssetIDEQ applies the EQ predicate on the "media_asset_id" field.
func MediaAssetIDEQ(v uuid.UUID) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldMediaAssetID, v))
}

// MediaAssetIDNEQ applies the NEQ predicate on the "media_asset_id" field.
func MediaAssetIDNEQ(v uuid.UUID) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNEQ(FieldMediaAssetID, v))
}

// MediaAssetIDIn applies the In predicate on the "media_asset_id" field.
func MediaAssetIDIn(vs ...uuid.UUID) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldIn(FieldMediaAssetID, vs...))
}

// MediaAssetIDNotIn applies the NotIn predicate on the "media_asset_id" field.
func MediaAssetIDNotIn(vs ...uuid.UUID) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNotIn(FieldMediaAssetID, vs...))
}

// MediaAssetIDGT applies the GT predicate on the "media_asset_id" field.
func MediaAssetIDGT(v uuid.UUID) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGT(FieldMediaAssetID, v))
}

// MediaAssetIDGTE applies the GTE predicate on the "media_asset_id" field.
func MediaAssetIDGTE(v uuid.UUID) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGTE(FieldMediaAssetID, v))
}

// MediaAssetIDLT applies the LT predicate on the "media_asset_id" field.
func MediaAssetIDLT(v uuid.UUID) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLT(FieldMediaAssetID, v))
}

// MediaAssetIDLTE applies the LTE predicate on the "media_asset_id" field.
func MediaAssetIDLTE(v uuid.UUID) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLTE(FieldMediaAssetID, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLTE(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PostMedia) predicate.PostMedia {
	return predicate.PostMedia(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PostMedia) predicate.PostMedia {
	return predicate.PostMedia(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PostMedia) predicate.PostMedia {
	return predicate.PostMedia(sql.NotPredicates(p))
}
