// Code generated by ent, DO NOT EDIT.

package follow

import (
	"social-server/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Follow {
	return predicate.Follow(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Follow {
	return predicate.Follow(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Follow {
	return predicate.Follow(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Follow {
	return predicate.Follow(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Follow {
	return predicate.Follow(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Follow {
	return predicate.Follow(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Follow {
	return predicate.Follow(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Follow {
	return predicate.Follow(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Follow {
	return predicate.Follow(sql.FieldLTE(FieldID, id))
}

// FollowerID applies equality check predicate on the "follower_id" field. It's identical to FollowerIDEQ.
func FollowerID(v uuid.UUID) predicate.Follow {
	return predicate.Follow(sql.FieldEQ(FieldFollowerID, v))
}

// FollowingID applies equality check predicate on the "following_id" field. It's identical to FollowingIDEQ.
func FollowingID(v uuid.UUID) predicate.Follow {
	return predicate.Follow(sql.FieldEQ(FieldFollowingID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldEQ(FieldCreatedAt, v))
}

// FollowerIDEQ applies the EQ predicate on the "follower_id" field.
func FollowerIDEQ(v uuid.UUID) predicate.Follow {
	return predicate.Follow(sql.FieldEQ(FieldFollowerID, v))
}

// FollowerIDNEQ applies the NEQ predicate on the "follower_id" field.
func FollowerIDNEQ(v uuid.UUID) predicate.Follow {
	return predicate.Follow(sql.FieldNEQ(FieldFollowerID, v))
}

// FollowerIDIn applies the In predicate on the "follower_id" field.
func FollowerIDIn(vs ...uuid.UUID) predicate.Follow {
	return predicate.Follow(sql.FieldIn(FieldFollowerID, vs...))
}

// FollowerIDNotIn applies the NotIn predicate on the "follower_id" field.
func FollowerIDNotIn(vs ...uuid.UUID) predicate.Follow {
	return predicate.Follow(sql.FieldNotIn(FieldFollowerID, vs...))
}

// FollowerIDGT applies the GT predicate on the "follower_id" field.
func FollowerIDGT(v uuid.UUID) predicate.Follow {
	return predicate.Follow(sql.FieldGT(FieldFollowerID, v))
}

// FollowerIDGTE applies the GTE predicate on the "follower_id" field.
func FollowerIDGTE(v uuid.UUID) predicate.Follow {
	return predicate.Follow(sql.FieldGTE(FieldFollowerID, v))
}

// FollowerIDLT applies the LT predicate on the "follower_id" field.
func FollowerIDLT(v uuid.UUID) predicate.Follow {
	return predicate.Follow(sql.FieldLT(FieldFollowerID, v))
}

// FollowerIDLTE applies the LTE predicate on the "follower_id" field.
func FollowerIDLTE(v uuid.UUID) predicate.Follow {
	return predicate.Follow(sql.FieldLTE(FieldFollowerID, v))
}

// FollowingIDEQ applies the EQ predicate on the "following_id" field.
func FollowingIDEQ(v uuid.UUID) predicate.Follow {
	return predicate.Follow(sql.FieldEQ(FieldFollowingID, v))
}

// FollowingIDNEQ applies the NEQ predicate on the "following_id" field.
func FollowingIDNEQ(v uuid.UUID) predicate.Follow {
	return predicate.Follow(sql.FieldNEQ(FieldFollowingID, v))
}

// FollowingIDIn applies the In predicate on the "following_id" field.
func FollowingIDIn(vs ...uuid.UUID) predicate.Follow {
	return predicate.Follow(sql.FieldIn(FieldFollowingID, vs...))
}

// FollowingIDNotIn applies the NotIn predicate on the "following_id" field.
func FollowingIDNotIn(vs ...uuid.UUID) predicate.Follow {
	return predicate.Follow(sql.FieldNotIn(FieldFollowingID, vs...))
}

// FollowingIDGT applies the GT predicate on the "following_id" field.
func FollowingIDGT(v uuid.UUID) predicate.Follow {
	return predicate.Follow(sql.FieldGT(FieldFollowingID, v))
}

// FollowingIDGTE applies the GTE predicate on the "following_id" field.
func FollowingIDGTE(v uuid.UUID) predicate.Follow {
	return predicate.Follow(sql.FieldGTE(FieldFollowingID, v))
}

// FollowingIDLT applies the LT predicate on the "following_id" field.
func FollowingIDLT(v uuid.UUID) predicate.Follow {
	return predicate.Follow(sql.FieldLT(FieldFollowingID, v))
}

// FollowingIDLTE applies the LTE predicate on the "following_id" field.
func FollowingIDLTE(v uuid.UUID) predicate.Follow {
	return predicate.Follow(sql.FieldLTE(FieldFollowingID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Follow) predicate.Follow {
	return predicate.Follow(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Follow) predicate.Follow {
	return predicate.Follow(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Follow) predicate.Follow {
	return predicate.Follow(sql.NotPredicates(p))
}
