// Code generated by ent, DO NOT EDIT.

package processedevent

import (
	"social-server/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldLTE(FieldID, id))
}

// EventID applies equality check predicate on the "event_id" field. It's identical to EventIDEQ.
func EventID(v uuid.UUID) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldEQ(FieldEventID, v))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldEQ(FieldEventType, v))
}

// ConsumerGroup applies equality check predicate on the "consumer_group" field. It's identical to ConsumerGroupEQ.
func ConsumerGroup(v string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldEQ(FieldConsumerGroup, v))
}

// ProcessedAt applies equality check predicate on the "processed_at" field. It's identical to ProcessedAtEQ.
func ProcessedAt(v time.Time) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldEQ(FieldProcessedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// EventIDEQ applies the EQ predicate on the "event_id" field.
func EventIDEQ(v uuid.UUID) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldEQ(FieldEventID, v))
}

// EventIDNEQ applies the NEQ predicate on the "event_id" field.
func EventIDNEQ(v uuid.UUID) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldNEQ(FieldEventID, v))
}

// EventIDIn applies the In predicate on the "event_id" field.
func EventIDIn(vs ...uuid.UUID) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldIn(FieldEventID, vs...))
}

// EventIDNotIn applies the NotIn predicate on the "event_id" field.
func EventIDNotIn(vs ...uuid.UUID) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldNotIn(FieldEventID, vs...))
}

// EventIDGT applies the GT predicate on the "event_id" field.
func EventIDGT(v uuid.UUID) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldGT(FieldEventID, v))
}

// EventIDGTE applies the GTE predicate on the "event_id" field.
func EventIDGTE(v uuid.UUID) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldGTE(FieldEventID, v))
}

// EventIDLT applies the LT predicate on the "event_id" field.
func EventIDLT(v uuid.UUID) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldLT(FieldEventID, v))
}

// EventIDLTE applies the LTE predicate on the "event_id" field.
func EventIDLTE(v uuid.UUID) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldLTE(FieldEventID, v))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldContainsFold(FieldEventType, v))
}

// ConsumerGroupEQ applies the EQ predicate on the "consumer_group" field.
func ConsumerGroupEQ(v string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldEQ(FieldConsumerGroup, v))
}

// ConsumerGroupNEQ applies the NEQ predicate on the "consumer_group" field.
func ConsumerGroupNEQ(v string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldNEQ(FieldConsumerGroup, v))
}

// ConsumerGroupIn applies the In predicate on the "consumer_group" field.
func ConsumerGroupIn(vs ...string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldIn(FieldConsumerGroup, vs...))
}

// ConsumerGroupNotIn applies the NotIn predicate on the "consumer_group" field.
func ConsumerGroupNotIn(vs ...string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldNotIn(FieldConsumerGroup, vs...))
}

// ConsumerGroupGT applies the GT predicate on the "consumer_group" field.
func ConsumerGroupGT(v string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldGT(FieldConsumerGroup, v))
}

// ConsumerGroupGTE applies the GTE predicate on the "consumer_group" field.
func ConsumerGroupGTE(v string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldGTE(FieldConsumerGroup, v))
}

// ConsumerGroupLT applies the LT predicate on the "consumer_group" field.
func ConsumerGroupLT(v string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldLT(FieldConsumerGroup, v))
}

// ConsumerGroupLTE applies the LTE predicate on the "consumer_group" field.
func ConsumerGroupLTE(v string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldLTE(FieldConsumerGroup, v))
}

// ConsumerGroupContains applies the Contains predicate on the "consumer_group" field.
func ConsumerGroupContains(v string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldContains(FieldConsumerGroup, v))
}

// ConsumerGroupHasPrefix applies the HasPrefix predicate on the "consumer_group" field.
func ConsumerGroupHasPrefix(v string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldHasPrefix(FieldConsumerGroup, v))
}

// ConsumerGroupHasSuffix applies the HasSuffix predicate on the "consumer_group" field.
func ConsumerGroupHasSuffix(v string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldHasSuffix(FieldConsumerGroup, v))
}

// ConsumerGroupEqualFold applies the EqualFold predicate on the "consumer_group" field.
func ConsumerGroupEqualFold(v string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldEqualFold(FieldConsumerGroup, v))
}

// ConsumerGroupContainsFold applies the ContainsFold predicate on the "consumer_group" field.
func ConsumerGroupContainsFold(v string) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldContainsFold(FieldConsumerGroup, v))
}

// ProcessedAtEQ applies the EQ predicate on the "processed_at" field.
func ProcessedAtEQ(v time.Time) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldEQ(FieldProcessedAt, v))
}

// ProcessedAtNEQ applies the NEQ predicate on the "processed_at" field.
func ProcessedAtNEQ(v time.Time) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldNEQ(FieldProcessedAt, v))
}

// ProcessedAtIn applies the In predicate on the "processed_at" field.
func ProcessedAtIn(vs ...time.Time) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldIn(FieldProcessedAt, vs...))
}

// ProcessedAtNotIn applies the NotIn predicate on the "processed_at" field.
func ProcessedAtNotIn(vs ...time.Time) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldNotIn(FieldProcessedAt, vs...))
}

// ProcessedAtGT applies the GT predicate on the "processed_at" field.
func ProcessedAtGT(v time.Time) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldGT(FieldProcessedAt, v))
}

// ProcessedAtGTE applies the GTE predicate on the "processed_at" field.
func ProcessedAtGTE(v time.Time) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldGTE(FieldProcessedAt, v))
}

// ProcessedAtLT applies the LT predicate on the "processed_at" field.
func ProcessedAtLT(v time.Time) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldLT(FieldProcessedAt, v))
}

// ProcessedAtLTE applies the LTE predicate on the "processed_at" field.
func ProcessedAtLTE(v time.Time) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldLTE(FieldProcessedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProcessedEvent) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProcessedEvent) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProcessedEvent) predicate.ProcessedEvent {
	return predicate.ProcessedEvent(sql.NotPredicates(p))
}
