// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MediaAssetsColumns holds the columns for the "media_assets" table.
	MediaAssetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "owner_id", Type: field.TypeUUID},
		{Name: "filename", Type: field.TypeString, Size: 255},
		{Name: "mime_type", Type: field.TypeString, Size: 64},
		{Name: "size", Type: field.TypeInt64, Default: 0},
		{Name: "url", Type: field.TypeString, Size: 512, Default: ""},
		{Name: "thumbnail_url", Type: field.TypeString, Size: 512, Default: ""},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// MediaAssetsTable holds the schema information for the "media_assets" table.
	MediaAssetsTable = &schema.Table{
		Name:       "media_assets",
		Columns:    MediaAssetsColumns,
		PrimaryKey: []*schema.Column{MediaAssetsColumns[0]},
	}
	// OutboxEventsColumns holds the columns for the "outbox_events" table.
	OutboxEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "topic", Type: field.TypeString, Size: 128},
		{Name: "key", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "payload", Type: field.TypeJSON},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "retry_count", Type: field.TypeInt, Default: 0},
		{Name: "last_error", Type: field.TypeString, Size: 512, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "published_at", Type: field.TypeTime, Nullable: true},
	}
	// OutboxEventsTable holds the schema information for the "outbox_events" table.
	OutboxEventsTable = &schema.Table{
		Name:       "outbox_events",
		Columns:    OutboxEventsColumns,
		PrimaryKey: []*schema.Column{OutboxEventsColumns[0]},
	}
	// PostsColumns holds the columns for the "posts" table.
	PostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "content", Type: field.TypeString, Size: 2000, Default: ""},
		{Name: "reply_to_id", Type: field.TypeUUID, Nullable: true},
		{Name: "repost_of_id", Type: field.TypeUUID, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "visibility", Type: field.TypeString, Default: "public"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// PostsTable holds the schema information for the "posts" table.
	PostsTable = &schema.Table{
		Name:       "posts",
		Columns:    PostsColumns,
		PrimaryKey: []*schema.Column{PostsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "post_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{PostsColumns[1], PostsColumns[7]},
			},
			{
				Name:    "post_reply_to_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{PostsColumns[3], PostsColumns[7]},
			},
			{
				Name:    "post_repost_of_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{PostsColumns[4], PostsColumns[7]},
			},
			{
				Name:    "post_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{PostsColumns[5], PostsColumns[7]},
			},
		},
	}
	// PostMediaColumns holds the columns for the "post_media" table.
	PostMediaColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "post_id", Type: field.TypeUUID},
		{Name: "media_asset_id", Type: field.TypeUUID},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
	}
	// PostMediaTable holds the schema information for the "post_media" table.
	PostMediaTable = &schema.Table{
		Name:       "post_media",
		Columns:    PostMediaColumns,
		PrimaryKey: []*schema.Column{PostMediaColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "postmedia_post_id_sort_order",
				Unique:  false,
				Columns: []*schema.Column{PostMediaColumns[1], PostMediaColumns[3]},
			},
			{
				Name:    "postmedia_media_asset_id",
				Unique:  false,
				Columns: []*schema.Column{PostMediaColumns[2]},
			},
		},
	}
	// PostStatsColumns holds the columns for the "post_stats" table.
	PostStatsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "post_id", Type: field.TypeUUID, Unique: true},
		{Name: "like_count", Type: field.TypeInt, Default: 0},
		{Name: "reply_count", Type: field.TypeInt, Default: 0},
		{Name: "repost_count", Type: field.TypeInt, Default: 0},
		{Name: "bookmark_count", Type: field.TypeInt, Default: 0},
		{Name: "view_count", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PostStatsTable holds the schema information for the "post_stats" table.
	PostStatsTable = &schema.Table{
		Name:       "post_stats",
		Columns:    PostStatsColumns,
		PrimaryKey: []*schema.Column{PostStatsColumns[0]},
	}
	// ProcessedEventsColumns holds the columns for the "processed_events" table.
	ProcessedEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "event_id", Type: field.TypeUUID},
		{Name: "event_type", Type: field.TypeString, Size: 128},
		{Name: "consumer_group", Type: field.TypeString, Size: 128},
		{Name: "processed_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ProcessedEventsTable holds the schema information for the "processed_events" table.
	ProcessedEventsTable = &schema.Table{
		Name:       "processed_events",
		Columns:    ProcessedEventsColumns,
		PrimaryKey: []*schema.Column{ProcessedEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "processedevent_event_id_consumer_group",
				Unique:  true,
				Columns: []*schema.Column{ProcessedEventsColumns[1], ProcessedEventsColumns[3]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "username", Type: field.TypeString, Unique: true, Size: 30},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_username",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[1]},
			},
			{
				Name:    "user_email",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[2]},
			},
		},
	}
	// UserProfilesColumns holds the columns for the "user_profiles" table.
	UserProfilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "display_name", Type: field.TypeString, Size: 50, Default: ""},
		{Name: "bio", Type: field.TypeString, Size: 160, Default: ""},
		{Name: "avatar_url", Type: field.TypeString, Size: 512, Default: ""},
		{Name: "cover_url", Type: field.TypeString, Size: 512, Default: ""},
		{Name: "location", Type: field.TypeString, Size: 100, Default: ""},
		{Name: "website", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UserProfilesTable holds the schema information for the "user_profiles" table.
	UserProfilesTable = &schema.Table{
		Name:       "user_profiles",
		Columns:    UserProfilesColumns,
		PrimaryKey: []*schema.Column{UserProfilesColumns[0]},
	}
	// UserSessionsColumns holds the columns for the "user_sessions" table.
	UserSessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "token_id", Type: field.TypeString, Size: 128},
		{Name: "device_info", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "ip_address", Type: field.TypeString, Size: 45, Default: ""},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UserSessionsTable holds the schema information for the "user_sessions" table.
	UserSessionsTable = &schema.Table{
		Name:       "user_sessions",
		Columns:    UserSessionsColumns,
		PrimaryKey: []*schema.Column{UserSessionsColumns[0]},
	}
	// UserStatsColumns holds the columns for the "user_stats" table.
	UserStatsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "user_id", Type: field.TypeUUID, Unique: true},
		{Name: "post_count", Type: field.TypeInt, Default: 0},
		{Name: "follower_count", Type: field.TypeInt, Default: 0},
		{Name: "following_count", Type: field.TypeInt, Default: 0},
		{Name: "like_received_count", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UserStatsTable holds the schema information for the "user_stats" table.
	UserStatsTable = &schema.Table{
		Name:       "user_stats",
		Columns:    UserStatsColumns,
		PrimaryKey: []*schema.Column{UserStatsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MediaAssetsTable,
		OutboxEventsTable,
		PostsTable,
		PostMediaTable,
		PostStatsTable,
		ProcessedEventsTable,
		UsersTable,
		UserProfilesTable,
		UserSessionsTable,
		UserStatsTable,
	}
)

func init() {
}
