// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"social-server/internal/ent/conversationmember"
	"social-server/internal/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ConversationMemberQuery is the builder for querying ConversationMember entities.
type ConversationMemberQuery struct {
	config
	ctx        *QueryContext
	order      []conversationmember.OrderOption
	inters     []Interceptor
	predicates []predicate.ConversationMember
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ConversationMemberQuery builder.
func (cmq *ConversationMemberQuery) Where(ps ...predicate.ConversationMember) *ConversationMemberQuery {
	cmq.predicates = append(cmq.predicates, ps...)
	return cmq
}

// Limit the number of records to be returned by this query.
func (cmq *ConversationMemberQuery) Limit(limit int) *ConversationMemberQuery {
	cmq.ctx.Limit = &limit
	return cmq
}

// Offset to start from.
func (cmq *ConversationMemberQuery) Offset(offset int) *ConversationMemberQuery {
	cmq.ctx.Offset = &offset
	return cmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cmq *ConversationMemberQuery) Unique(unique bool) *ConversationMemberQuery {
	cmq.ctx.Unique = &unique
	return cmq
}

// Order specifies how the records should be ordered.
func (cmq *ConversationMemberQuery) Order(o ...conversationmember.OrderOption) *ConversationMemberQuery {
	cmq.order = append(cmq.order, o...)
	return cmq
}

// First returns the first ConversationMember entity from the query.
// Returns a *NotFoundError when no ConversationMember was found.
func (cmq *ConversationMemberQuery) First(ctx context.Context) (*ConversationMember, error) {
	nodes, err := cmq.Limit(1).All(setContextOp(ctx, cmq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{conversationmember.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cmq *ConversationMemberQuery) FirstX(ctx context.Context) *ConversationMember {
	node, err := cmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ConversationMember ID from the query.
// Returns a *NotFoundError when no ConversationMember ID was found.
func (cmq *ConversationMemberQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = cmq.Limit(1).IDs(setContextOp(ctx, cmq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{conversationmember.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cmq *ConversationMemberQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := cmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ConversationMember entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ConversationMember entity is found.
// Returns a *NotFoundError when no ConversationMember entities are found.
func (cmq *ConversationMemberQuery) Only(ctx context.Context) (*ConversationMember, error) {
	nodes, err := cmq.Limit(2).All(setContextOp(ctx, cmq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{conversationmember.Label}
	default:
		return nil, &NotSingularError{conversationmember.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cmq *ConversationMemberQuery) OnlyX(ctx context.Context) *ConversationMember {
	node, err := cmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ConversationMember ID in the query.
// Returns a *NotSingularError when more than one ConversationMember ID is found.
// Returns a *NotFoundError when no entities are found.
func (cmq *ConversationMemberQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = cmq.Limit(2).IDs(setContextOp(ctx, cmq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{conversationmember.Label}
	default:
		err = &NotSingularError{conversationmember.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cmq *ConversationMemberQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := cmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ConversationMembers.
func (cmq *ConversationMemberQuery) All(ctx context.Context) ([]*ConversationMember, error) {
	ctx = setContextOp(ctx, cmq.ctx, ent.OpQueryAll)
	if err := cmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ConversationMember, *ConversationMemberQuery]()
	return withInterceptors[[]*ConversationMember](ctx, cmq, qr, cmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cmq *ConversationMemberQuery) AllX(ctx context.Context) []*ConversationMember {
	nodes, err := cmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ConversationMember IDs.
func (cmq *ConversationMemberQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if cmq.ctx.Unique == nil && cmq.path != nil {
		cmq.Unique(true)
	}
	ctx = setContextOp(ctx, cmq.ctx, ent.OpQueryIDs)
	if err = cmq.Select(conversationmember.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cmq *ConversationMemberQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := cmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cmq *ConversationMemberQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cmq.ctx, ent.OpQueryCount)
	if err := cmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cmq, querierCount[*ConversationMemberQuery](), cmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cmq *ConversationMemberQuery) CountX(ctx context.Context) int {
	count, err := cmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cmq *ConversationMemberQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cmq.ctx, ent.OpQueryExist)
	switch _, err := cmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cmq *ConversationMemberQuery) ExistX(ctx context.Context) bool {
	exist, err := cmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ConversationMemberQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cmq *ConversationMemberQuery) Clone() *ConversationMemberQuery {
	if cmq == nil {
		return nil
	}
	return &ConversationMemberQuery{
		config:     cmq.config,
		ctx:        cmq.ctx.Clone(),
		order:      append([]conversationmember.OrderOption{}, cmq.order...),
		inters:     append([]Interceptor{}, cmq.inters...),
		predicates: append([]predicate.ConversationMember{}, cmq.predicates...),
		// clone intermediate query.
		sql:  cmq.sql.Clone(),
		path: cmq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ConversationID uuid.UUID `json:"conversation_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ConversationMember.Query().
//		GroupBy(conversationmember.FieldConversationID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cmq *ConversationMemberQuery) GroupBy(field string, fields ...string) *ConversationMemberGroupBy {
	cmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ConversationMemberGroupBy{build: cmq}
	grbuild.flds = &cmq.ctx.Fields
	grbuild.label = conversationmember.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ConversationID uuid.UUID `json:"conversation_id,omitempty"`
//	}
//
//	client.ConversationMember.Query().
//		Select(conversationmember.FieldConversationID).
//		Scan(ctx, &v)
func (cmq *ConversationMemberQuery) Select(fields ...string) *ConversationMemberSelect {
	cmq.ctx.Fields = append(cmq.ctx.Fields, fields...)
	sbuild := &ConversationMemberSelect{ConversationMemberQuery: cmq}
	sbuild.label = conversationmember.Label
	sbuild.flds, sbuild.scan = &cmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ConversationMemberSelect configured with the given aggregations.
func (cmq *ConversationMemberQuery) Aggregate(fns ...AggregateFunc) *ConversationMemberSelect {
	return cmq.Select().Aggregate(fns...)
}

func (cmq *ConversationMemberQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cmq); err != nil {
				return err
			}
		}
	}
	for _, f := range cmq.ctx.Fields {
		if !conversationmember.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cmq.path != nil {
		prev, err := cmq.path(ctx)
		if err != nil {
			return err
		}
		cmq.sql = prev
	}
	return nil
}

func (cmq *ConversationMemberQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ConversationMember, error) {
	var (
		nodes = []*ConversationMember{}
		_spec = cmq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ConversationMember).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ConversationMember{config: cmq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (cmq *ConversationMemberQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cmq.querySpec()
	_spec.Node.Columns = cmq.ctx.Fields
	if len(cmq.ctx.Fields) > 0 {
		_spec.Unique = cmq.ctx.Unique != nil && *cmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cmq.driver, _spec)
}

func (cmq *ConversationMemberQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(conversationmember.Table, conversationmember.Columns, sqlgraph.NewFieldSpec(conversationmember.FieldID, field.TypeUUID))
	_spec.From = cmq.sql
	if unique := cmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cmq.path != nil {
		_spec.Unique = true
	}
	if fields := cmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, conversationmember.FieldID)
		for i := range fields {
			if fields[i] != conversationmember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cmq *ConversationMemberQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cmq.driver.Dialect())
	t1 := builder.Table(conversationmember.Table)
	columns := cmq.ctx.Fields
	if len(columns) == 0 {
		columns = conversationmember.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cmq.sql != nil {
		selector = cmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cmq.ctx.Unique != nil && *cmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cmq.predicates {
		p(selector)
	}
	for _, p := range cmq.order {
		p(selector)
	}
	if offset := cmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ConversationMemberGroupBy is the group-by builder for ConversationMember entities.
type ConversationMemberGroupBy struct {
	selector
	build *ConversationMemberQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cmgb *ConversationMemberGroupBy) Aggregate(fns ...AggregateFunc) *ConversationMemberGroupBy {
	cmgb.fns = append(cmgb.fns, fns...)
	return cmgb
}

// Scan applies the selector query and scans the result into the given value.
func (cmgb *ConversationMemberGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cmgb.build.ctx, ent.OpQueryGroupBy)
	if err := cmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ConversationMemberQuery, *ConversationMemberGroupBy](ctx, cmgb.build, cmgb, cmgb.build.inters, v)
}

func (cmgb *ConversationMemberGroupBy) sqlScan(ctx context.Context, root *ConversationMemberQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cmgb.fns))
	for _, fn := range cmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cmgb.flds)+len(cmgb.fns))
		for _, f := range *cmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ConversationMemberSelect is the builder for selecting fields of ConversationMember entities.
type ConversationMemberSelect struct {
	*ConversationMemberQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cms *ConversationMemberSelect) Aggregate(fns ...AggregateFunc) *ConversationMemberSelect {
	cms.fns = append(cms.fns, fns...)
	return cms
}

// Scan applies the selector query and scans the result into the given value.
func (cms *ConversationMemberSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cms.ctx, ent.OpQuerySelect)
	if err := cms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ConversationMemberQuery, *ConversationMemberSelect](ctx, cms.ConversationMemberQuery, cms, cms.inters, v)
}

func (cms *ConversationMemberSelect) sqlScan(ctx context.Context, root *ConversationMemberQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cms.fns))
	for _, fn := range cms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
