// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"social-server/internal/ent/moderationaction"
	"social-server/internal/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ModerationActionQuery is the builder for querying ModerationAction entities.
type ModerationActionQuery struct {
	config
	ctx        *QueryContext
	order      []moderationaction.OrderOption
	inters     []Interceptor
	predicates []predicate.ModerationAction
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ModerationActionQuery builder.
func (maq *ModerationActionQuery) Where(ps ...predicate.ModerationAction) *ModerationActionQuery {
	maq.predicates = append(maq.predicates, ps...)
	return maq
}

// Limit the number of records to be returned by this query.
func (maq *ModerationActionQuery) Limit(limit int) *ModerationActionQuery {
	maq.ctx.Limit = &limit
	return maq
}

// Offset to start from.
func (maq *ModerationActionQuery) Offset(offset int) *ModerationActionQuery {
	maq.ctx.Offset = &offset
	return maq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (maq *ModerationActionQuery) Unique(unique bool) *ModerationActionQuery {
	maq.ctx.Unique = &unique
	return maq
}

// Order specifies how the records should be ordered.
func (maq *ModerationActionQuery) Order(o ...moderationaction.OrderOption) *ModerationActionQuery {
	maq.order = append(maq.order, o...)
	return maq
}

// First returns the first ModerationAction entity from the query.
// Returns a *NotFoundError when no ModerationAction was found.
func (maq *ModerationActionQuery) First(ctx context.Context) (*ModerationAction, error) {
	nodes, err := maq.Limit(1).All(setContextOp(ctx, maq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{moderationaction.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (maq *ModerationActionQuery) FirstX(ctx context.Context) *ModerationAction {
	node, err := maq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ModerationAction ID from the query.
// Returns a *NotFoundError when no ModerationAction ID was found.
func (maq *ModerationActionQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = maq.Limit(1).IDs(setContextOp(ctx, maq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{moderationaction.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (maq *ModerationActionQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := maq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ModerationAction entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ModerationAction entity is found.
// Returns a *NotFoundError when no ModerationAction entities are found.
func (maq *ModerationActionQuery) Only(ctx context.Context) (*ModerationAction, error) {
	nodes, err := maq.Limit(2).All(setContextOp(ctx, maq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{moderationaction.Label}
	default:
		return nil, &NotSingularError{moderationaction.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (maq *ModerationActionQuery) OnlyX(ctx context.Context) *ModerationAction {
	node, err := maq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ModerationAction ID in the query.
// Returns a *NotSingularError when more than one ModerationAction ID is found.
// Returns a *NotFoundError when no entities are found.
func (maq *ModerationActionQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = maq.Limit(2).IDs(setContextOp(ctx, maq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{moderationaction.Label}
	default:
		err = &NotSingularError{moderationaction.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (maq *ModerationActionQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := maq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ModerationActions.
func (maq *ModerationActionQuery) All(ctx context.Context) ([]*ModerationAction, error) {
	ctx = setContextOp(ctx, maq.ctx, ent.OpQueryAll)
	if err := maq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ModerationAction, *ModerationActionQuery]()
	return withInterceptors[[]*ModerationAction](ctx, maq, qr, maq.inters)
}

// AllX is like All, but panics if an error occurs.
func (maq *ModerationActionQuery) AllX(ctx context.Context) []*ModerationAction {
	nodes, err := maq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ModerationAction IDs.
func (maq *ModerationActionQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if maq.ctx.Unique == nil && maq.path != nil {
		maq.Unique(true)
	}
	ctx = setContextOp(ctx, maq.ctx, ent.OpQueryIDs)
	if err = maq.Select(moderationaction.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (maq *ModerationActionQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := maq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (maq *ModerationActionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, maq.ctx, ent.OpQueryCount)
	if err := maq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, maq, querierCount[*ModerationActionQuery](), maq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (maq *ModerationActionQuery) CountX(ctx context.Context) int {
	count, err := maq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (maq *ModerationActionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, maq.ctx, ent.OpQueryExist)
	switch _, err := maq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (maq *ModerationActionQuery) ExistX(ctx context.Context) bool {
	exist, err := maq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ModerationActionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (maq *ModerationActionQuery) Clone() *ModerationActionQuery {
	if maq == nil {
		return nil
	}
	return &ModerationActionQuery{
		config:     maq.config,
		ctx:        maq.ctx.Clone(),
		order:      append([]moderationaction.OrderOption{}, maq.order...),
		inters:     append([]Interceptor{}, maq.inters...),
		predicates: append([]predicate.ModerationAction{}, maq.predicates...),
		// clone intermediate query.
		sql:  maq.sql.Clone(),
		path: maq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ModeratorID uuid.UUID `json:"moderator_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ModerationAction.Query().
//		GroupBy(moderationaction.FieldModeratorID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (maq *ModerationActionQuery) GroupBy(field string, fields ...string) *ModerationActionGroupBy {
	maq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ModerationActionGroupBy{build: maq}
	grbuild.flds = &maq.ctx.Fields
	grbuild.label = moderationaction.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ModeratorID uuid.UUID `json:"moderator_id,omitempty"`
//	}
//
//	client.ModerationAction.Query().
//		Select(moderationaction.FieldModeratorID).
//		Scan(ctx, &v)
func (maq *ModerationActionQuery) Select(fields ...string) *ModerationActionSelect {
	maq.ctx.Fields = append(maq.ctx.Fields, fields...)
	sbuild := &ModerationActionSelect{ModerationActionQuery: maq}
	sbuild.label = moderationaction.Label
	sbuild.flds, sbuild.scan = &maq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ModerationActionSelect configured with the given aggregations.
func (maq *ModerationActionQuery) Aggregate(fns ...AggregateFunc) *ModerationActionSelect {
	return maq.Select().Aggregate(fns...)
}

func (maq *ModerationActionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range maq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, maq); err != nil {
				return err
			}
		}
	}
	for _, f := range maq.ctx.Fields {
		if !moderationaction.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if maq.path != nil {
		prev, err := maq.path(ctx)
		if err != nil {
			return err
		}
		maq.sql = prev
	}
	return nil
}

func (maq *ModerationActionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ModerationAction, error) {
	var (
		nodes = []*ModerationAction{}
		_spec = maq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ModerationAction).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ModerationAction{config: maq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, maq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (maq *ModerationActionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := maq.querySpec()
	_spec.Node.Columns = maq.ctx.Fields
	if len(maq.ctx.Fields) > 0 {
		_spec.Unique = maq.ctx.Unique != nil && *maq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, maq.driver, _spec)
}

func (maq *ModerationActionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(moderationaction.Table, moderationaction.Columns, sqlgraph.NewFieldSpec(moderationaction.FieldID, field.TypeUUID))
	_spec.From = maq.sql
	if unique := maq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if maq.path != nil {
		_spec.Unique = true
	}
	if fields := maq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, moderationaction.FieldID)
		for i := range fields {
			if fields[i] != moderationaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := maq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := maq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := maq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := maq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (maq *ModerationActionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(maq.driver.Dialect())
	t1 := builder.Table(moderationaction.Table)
	columns := maq.ctx.Fields
	if len(columns) == 0 {
		columns = moderationaction.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if maq.sql != nil {
		selector = maq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if maq.ctx.Unique != nil && *maq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range maq.predicates {
		p(selector)
	}
	for _, p := range maq.order {
		p(selector)
	}
	if offset := maq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := maq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ModerationActionGroupBy is the group-by builder for ModerationAction entities.
type ModerationActionGroupBy struct {
	selector
	build *ModerationActionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (magb *ModerationActionGroupBy) Aggregate(fns ...AggregateFunc) *ModerationActionGroupBy {
	magb.fns = append(magb.fns, fns...)
	return magb
}

// Scan applies the selector query and scans the result into the given value.
func (magb *ModerationActionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, magb.build.ctx, ent.OpQueryGroupBy)
	if err := magb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ModerationActionQuery, *ModerationActionGroupBy](ctx, magb.build, magb, magb.build.inters, v)
}

func (magb *ModerationActionGroupBy) sqlScan(ctx context.Context, root *ModerationActionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(magb.fns))
	for _, fn := range magb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*magb.flds)+len(magb.fns))
		for _, f := range *magb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*magb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := magb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ModerationActionSelect is the builder for selecting fields of ModerationAction entities.
type ModerationActionSelect struct {
	*ModerationActionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mas *ModerationActionSelect) Aggregate(fns ...AggregateFunc) *ModerationActionSelect {
	mas.fns = append(mas.fns, fns...)
	return mas
}

// Scan applies the selector query and scans the result into the given value.
func (mas *ModerationActionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mas.ctx, ent.OpQuerySelect)
	if err := mas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ModerationActionQuery, *ModerationActionSelect](ctx, mas.ModerationActionQuery, mas, mas.inters, v)
}

func (mas *ModerationActionSelect) sqlScan(ctx context.Context, root *ModerationActionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mas.fns))
	for _, fn := range mas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
