// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"social-server/internal/ent/moderationaction"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ModerationActionCreate is the builder for creating a ModerationAction entity.
type ModerationActionCreate struct {
	config
	mutation *ModerationActionMutation
	hooks    []Hook
}

// SetModeratorID sets the "moderator_id" field.
func (mac *ModerationActionCreate) SetModeratorID(u uuid.UUID) *ModerationActionCreate {
	mac.mutation.SetModeratorID(u)
	return mac
}

// SetTargetUserID sets the "target_user_id" field.
func (mac *ModerationActionCreate) SetTargetUserID(u uuid.UUID) *ModerationActionCreate {
	mac.mutation.SetTargetUserID(u)
	return mac
}

// SetNillableTargetUserID sets the "target_user_id" field if the given value is not nil.
func (mac *ModerationActionCreate) SetNillableTargetUserID(u *uuid.UUID) *ModerationActionCreate {
	if u != nil {
		mac.SetTargetUserID(*u)
	}
	return mac
}

// SetTargetPostID sets the "target_post_id" field.
func (mac *ModerationActionCreate) SetTargetPostID(u uuid.UUID) *ModerationActionCreate {
	mac.mutation.SetTargetPostID(u)
	return mac
}

// SetNillableTargetPostID sets the "target_post_id" field if the given value is not nil.
func (mac *ModerationActionCreate) SetNillableTargetPostID(u *uuid.UUID) *ModerationActionCreate {
	if u != nil {
		mac.SetTargetPostID(*u)
	}
	return mac
}

// SetReportID sets the "report_id" field.
func (mac *ModerationActionCreate) SetReportID(u uuid.UUID) *ModerationActionCreate {
	mac.mutation.SetReportID(u)
	return mac
}

// SetNillableReportID sets the "report_id" field if the given value is not nil.
func (mac *ModerationActionCreate) SetNillableReportID(u *uuid.UUID) *ModerationActionCreate {
	if u != nil {
		mac.SetReportID(*u)
	}
	return mac
}

// SetActionType sets the "action_type" field.
func (mac *ModerationActionCreate) SetActionType(s string) *ModerationActionCreate {
	mac.mutation.SetActionType(s)
	return mac
}

// SetReason sets the "reason" field.
func (mac *ModerationActionCreate) SetReason(s string) *ModerationActionCreate {
	mac.mutation.SetReason(s)
	return mac
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (mac *ModerationActionCreate) SetNillableReason(s *string) *ModerationActionCreate {
	if s != nil {
		mac.SetReason(*s)
	}
	return mac
}

// SetCreatedAt sets the "created_at" field.
func (mac *ModerationActionCreate) SetCreatedAt(t time.Time) *ModerationActionCreate {
	mac.mutation.SetCreatedAt(t)
	return mac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mac *ModerationActionCreate) SetNillableCreatedAt(t *time.Time) *ModerationActionCreate {
	if t != nil {
		mac.SetCreatedAt(*t)
	}
	return mac
}

// SetID sets the "id" field.
func (mac *ModerationActionCreate) SetID(u uuid.UUID) *ModerationActionCreate {
	mac.mutation.SetID(u)
	return mac
}

// SetNillableID sets the "id" field if the given value is not nil.
func (mac *ModerationActionCreate) SetNillableID(u *uuid.UUID) *ModerationActionCreate {
	if u != nil {
		mac.SetID(*u)
	}
	return mac
}

// Mutation returns the ModerationActionMutation object of the builder.
func (mac *ModerationActionCreate) Mutation() *ModerationActionMutation {
	return mac.mutation
}

// Save creates the ModerationAction in the database.
func (mac *ModerationActionCreate) Save(ctx context.Context) (*ModerationAction, error) {
	mac.defaults()
	return withHooks(ctx, mac.sqlSave, mac.mutation, mac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mac *ModerationActionCreate) SaveX(ctx context.Context) *ModerationAction {
	v, err := mac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mac *ModerationActionCreate) Exec(ctx context.Context) error {
	_, err := mac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mac *ModerationActionCreate) ExecX(ctx context.Context) {
	if err := mac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mac *ModerationActionCreate) defaults() {
	if _, ok := mac.mutation.Reason(); !ok {
		v := moderationaction.DefaultReason
		mac.mutation.SetReason(v)
	}
	if _, ok := mac.mutation.CreatedAt(); !ok {
		v := moderationaction.DefaultCreatedAt()
		mac.mutation.SetCreatedAt(v)
	}
	if _, ok := mac.mutation.ID(); !ok {
		v := moderationaction.DefaultID()
		mac.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mac *ModerationActionCreate) check() error {
	if _, ok := mac.mutation.ModeratorID(); !ok {
		return &ValidationError{Name: "moderator_id", err: errors.New(`ent: missing required field "ModerationAction.moderator_id"`)}
	}
	if _, ok := mac.mutation.ActionType(); !ok {
		return &ValidationError{Name: "action_type", err: errors.New(`ent: missing required field "ModerationAction.action_type"`)}
	}
	if v, ok := mac.mutation.ActionType(); ok {
		if err := moderationaction.ActionTypeValidator(v); err != nil {
			return &ValidationError{Name: "action_type", err: fmt.Errorf(`ent: validator failed for field "ModerationAction.action_type": %w`, err)}
		}
	}
	if _, ok := mac.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "ModerationAction.reason"`)}
	}
	if _, ok := mac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ModerationAction.created_at"`)}
	}
	return nil
}

func (mac *ModerationActionCreate) sqlSave(ctx context.Context) (*ModerationAction, error) {
	if err := mac.check(); err != nil {
		return nil, err
	}
	_node, _spec := mac.createSpec()
	if err := sqlgraph.CreateNode(ctx, mac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	mac.mutation.id = &_node.ID
	mac.mutation.done = true
	return _node, nil
}

func (mac *ModerationActionCreate) createSpec() (*ModerationAction, *sqlgraph.CreateSpec) {
	var (
		_node = &ModerationAction{config: mac.config}
		_spec = sqlgraph.NewCreateSpec(moderationaction.Table, sqlgraph.NewFieldSpec(moderationaction.FieldID, field.TypeUUID))
	)
	if id, ok := mac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := mac.mutation.ModeratorID(); ok {
		_spec.SetField(moderationaction.FieldModeratorID, field.TypeUUID, value)
		_node.ModeratorID = value
	}
	if value, ok := mac.mutation.TargetUserID(); ok {
		_spec.SetField(moderationaction.FieldTargetUserID, field.TypeUUID, value)
		_node.TargetUserID = value
	}
	if value, ok := mac.mutation.TargetPostID(); ok {
		_spec.SetField(moderationaction.FieldTargetPostID, field.TypeUUID, value)
		_node.TargetPostID = value
	}
	if value, ok := mac.mutation.ReportID(); ok {
		_spec.SetField(moderationaction.FieldReportID, field.TypeUUID, value)
		_node.ReportID = value
	}
	if value, ok := mac.mutation.ActionType(); ok {
		_spec.SetField(moderationaction.FieldActionType, field.TypeString, value)
		_node.ActionType = value
	}
	if value, ok := mac.mutation.Reason(); ok {
		_spec.SetField(moderationaction.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := mac.mutation.CreatedAt(); ok {
		_spec.SetField(moderationaction.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// ModerationActionCreateBulk is the builder for creating many ModerationAction entities in bulk.
type ModerationActionCreateBulk struct {
	config
	err      error
	builders []*ModerationActionCreate
}

// Save creates the ModerationAction entities in the database.
func (macb *ModerationActionCreateBulk) Save(ctx context.Context) ([]*ModerationAction, error) {
	if macb.err != nil {
		return nil, macb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(macb.builders))
	nodes := make([]*ModerationAction, len(macb.builders))
	mutators := make([]Mutator, len(macb.builders))
	for i := range macb.builders {
		func(i int, root context.Context) {
			builder := macb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModerationActionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, macb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, macb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, macb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (macb *ModerationActionCreateBulk) SaveX(ctx context.Context) []*ModerationAction {
	v, err := macb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (macb *ModerationActionCreateBulk) Exec(ctx context.Context) error {
	_, err := macb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (macb *ModerationActionCreateBulk) ExecX(ctx context.Context) {
	if err := macb.Exec(ctx); err != nil {
		panic(err)
	}
}
