// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"social-server/internal/ent/postlike"
	"social-server/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PostLikeDelete is the builder for deleting a PostLike entity.
type PostLikeDelete struct {
	config
	hooks    []Hook
	mutation *PostLikeMutation
}

// Where appends a list predicates to the PostLikeDelete builder.
func (pld *PostLikeDelete) Where(ps ...predicate.PostLike) *PostLikeDelete {
	pld.mutation.Where(ps...)
	return pld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pld *PostLikeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pld.sqlExec, pld.mutation, pld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pld *PostLikeDelete) ExecX(ctx context.Context) int {
	n, err := pld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pld *PostLikeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(postlike.Table, sqlgraph.NewFieldSpec(postlike.FieldID, field.TypeUUID))
	if ps := pld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pld.mutation.done = true
	return affected, err
}

// PostLikeDeleteOne is the builder for deleting a single PostLike entity.
type PostLikeDeleteOne struct {
	pld *PostLikeDelete
}

// Where appends a list predicates to the PostLikeDelete builder.
func (pldo *PostLikeDeleteOne) Where(ps ...predicate.PostLike) *PostLikeDeleteOne {
	pldo.pld.mutation.Where(ps...)
	return pldo
}

// Exec executes the deletion query.
func (pldo *PostLikeDeleteOne) Exec(ctx context.Context) error {
	n, err := pldo.pld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{postlike.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pldo *PostLikeDeleteOne) ExecX(ctx context.Context) {
	if err := pldo.Exec(ctx); err != nil {
		panic(err)
	}
}
