// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"social-server/internal/ent/postlike"
	"social-server/internal/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PostLikeQuery is the builder for querying PostLike entities.
type PostLikeQuery struct {
	config
	ctx        *QueryContext
	order      []postlike.OrderOption
	inters     []Interceptor
	predicates []predicate.PostLike
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PostLikeQuery builder.
func (plq *PostLikeQuery) Where(ps ...predicate.PostLike) *PostLikeQuery {
	plq.predicates = append(plq.predicates, ps...)
	return plq
}

// Limit the number of records to be returned by this query.
func (plq *PostLikeQuery) Limit(limit int) *PostLikeQuery {
	plq.ctx.Limit = &limit
	return plq
}

// Offset to start from.
func (plq *PostLikeQuery) Offset(offset int) *PostLikeQuery {
	plq.ctx.Offset = &offset
	return plq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (plq *PostLikeQuery) Unique(unique bool) *PostLikeQuery {
	plq.ctx.Unique = &unique
	return plq
}

// Order specifies how the records should be ordered.
func (plq *PostLikeQuery) Order(o ...postlike.OrderOption) *PostLikeQuery {
	plq.order = append(plq.order, o...)
	return plq
}

// First returns the first PostLike entity from the query.
// Returns a *NotFoundError when no PostLike was found.
func (plq *PostLikeQuery) First(ctx context.Context) (*PostLike, error) {
	nodes, err := plq.Limit(1).All(setContextOp(ctx, plq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{postlike.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (plq *PostLikeQuery) FirstX(ctx context.Context) *PostLike {
	node, err := plq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PostLike ID from the query.
// Returns a *NotFoundError when no PostLike ID was found.
func (plq *PostLikeQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = plq.Limit(1).IDs(setContextOp(ctx, plq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{postlike.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (plq *PostLikeQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := plq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PostLike entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PostLike entity is found.
// Returns a *NotFoundError when no PostLike entities are found.
func (plq *PostLikeQuery) Only(ctx context.Context) (*PostLike, error) {
	nodes, err := plq.Limit(2).All(setContextOp(ctx, plq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{postlike.Label}
	default:
		return nil, &NotSingularError{postlike.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (plq *PostLikeQuery) OnlyX(ctx context.Context) *PostLike {
	node, err := plq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PostLike ID in the query.
// Returns a *NotSingularError when more than one PostLike ID is found.
// Returns a *NotFoundError when no entities are found.
func (plq *PostLikeQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = plq.Limit(2).IDs(setContextOp(ctx, plq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{postlike.Label}
	default:
		err = &NotSingularError{postlike.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (plq *PostLikeQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := plq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PostLikes.
func (plq *PostLikeQuery) All(ctx context.Context) ([]*PostLike, error) {
	ctx = setContextOp(ctx, plq.ctx, ent.OpQueryAll)
	if err := plq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PostLike, *PostLikeQuery]()
	return withInterceptors[[]*PostLike](ctx, plq, qr, plq.inters)
}

// AllX is like All, but panics if an error occurs.
func (plq *PostLikeQuery) AllX(ctx context.Context) []*PostLike {
	nodes, err := plq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PostLike IDs.
func (plq *PostLikeQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if plq.ctx.Unique == nil && plq.path != nil {
		plq.Unique(true)
	}
	ctx = setContextOp(ctx, plq.ctx, ent.OpQueryIDs)
	if err = plq.Select(postlike.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (plq *PostLikeQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := plq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (plq *PostLikeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, plq.ctx, ent.OpQueryCount)
	if err := plq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, plq, querierCount[*PostLikeQuery](), plq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (plq *PostLikeQuery) CountX(ctx context.Context) int {
	count, err := plq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (plq *PostLikeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, plq.ctx, ent.OpQueryExist)
	switch _, err := plq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (plq *PostLikeQuery) ExistX(ctx context.Context) bool {
	exist, err := plq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PostLikeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (plq *PostLikeQuery) Clone() *PostLikeQuery {
	if plq == nil {
		return nil
	}
	return &PostLikeQuery{
		config:     plq.config,
		ctx:        plq.ctx.Clone(),
		order:      append([]postlike.OrderOption{}, plq.order...),
		inters:     append([]Interceptor{}, plq.inters...),
		predicates: append([]predicate.PostLike{}, plq.predicates...),
		// clone intermediate query.
		sql:  plq.sql.Clone(),
		path: plq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PostID uuid.UUID `json:"post_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PostLike.Query().
//		GroupBy(postlike.FieldPostID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (plq *PostLikeQuery) GroupBy(field string, fields ...string) *PostLikeGroupBy {
	plq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PostLikeGroupBy{build: plq}
	grbuild.flds = &plq.ctx.Fields
	grbuild.label = postlike.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PostID uuid.UUID `json:"post_id,omitempty"`
//	}
//
//	client.PostLike.Query().
//		Select(postlike.FieldPostID).
//		Scan(ctx, &v)
func (plq *PostLikeQuery) Select(fields ...string) *PostLikeSelect {
	plq.ctx.Fields = append(plq.ctx.Fields, fields...)
	sbuild := &PostLikeSelect{PostLikeQuery: plq}
	sbuild.label = postlike.Label
	sbuild.flds, sbuild.scan = &plq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PostLikeSelect configured with the given aggregations.
func (plq *PostLikeQuery) Aggregate(fns ...AggregateFunc) *PostLikeSelect {
	return plq.Select().Aggregate(fns...)
}

func (plq *PostLikeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range plq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, plq); err != nil {
				return err
			}
		}
	}
	for _, f := range plq.ctx.Fields {
		if !postlike.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if plq.path != nil {
		prev, err := plq.path(ctx)
		if err != nil {
			return err
		}
		plq.sql = prev
	}
	return nil
}

func (plq *PostLikeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PostLike, error) {
	var (
		nodes = []*PostLike{}
		_spec = plq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PostLike).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PostLike{config: plq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, plq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (plq *PostLikeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := plq.querySpec()
	_spec.Node.Columns = plq.ctx.Fields
	if len(plq.ctx.Fields) > 0 {
		_spec.Unique = plq.ctx.Unique != nil && *plq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, plq.driver, _spec)
}

func (plq *PostLikeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(postlike.Table, postlike.Columns, sqlgraph.NewFieldSpec(postlike.FieldID, field.TypeUUID))
	_spec.From = plq.sql
	if unique := plq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if plq.path != nil {
		_spec.Unique = true
	}
	if fields := plq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, postlike.FieldID)
		for i := range fields {
			if fields[i] != postlike.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := plq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := plq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := plq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := plq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (plq *PostLikeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(plq.driver.Dialect())
	t1 := builder.Table(postlike.Table)
	columns := plq.ctx.Fields
	if len(columns) == 0 {
		columns = postlike.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if plq.sql != nil {
		selector = plq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if plq.ctx.Unique != nil && *plq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range plq.predicates {
		p(selector)
	}
	for _, p := range plq.order {
		p(selector)
	}
	if offset := plq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := plq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PostLikeGroupBy is the group-by builder for PostLike entities.
type PostLikeGroupBy struct {
	selector
	build *PostLikeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (plgb *PostLikeGroupBy) Aggregate(fns ...AggregateFunc) *PostLikeGroupBy {
	plgb.fns = append(plgb.fns, fns...)
	return plgb
}

// Scan applies the selector query and scans the result into the given value.
func (plgb *PostLikeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, plgb.build.ctx, ent.OpQueryGroupBy)
	if err := plgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PostLikeQuery, *PostLikeGroupBy](ctx, plgb.build, plgb, plgb.build.inters, v)
}

func (plgb *PostLikeGroupBy) sqlScan(ctx context.Context, root *PostLikeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(plgb.fns))
	for _, fn := range plgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*plgb.flds)+len(plgb.fns))
		for _, f := range *plgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*plgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := plgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PostLikeSelect is the builder for selecting fields of PostLike entities.
type PostLikeSelect struct {
	*PostLikeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pls *PostLikeSelect) Aggregate(fns ...AggregateFunc) *PostLikeSelect {
	pls.fns = append(pls.fns, fns...)
	return pls
}

// Scan applies the selector query and scans the result into the given value.
func (pls *PostLikeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pls.ctx, ent.OpQuerySelect)
	if err := pls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PostLikeQuery, *PostLikeSelect](ctx, pls.PostLikeQuery, pls, pls.inters, v)
}

func (pls *PostLikeSelect) sqlScan(ctx context.Context, root *PostLikeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pls.fns))
	for _, fn := range pls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
