// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"social-server/internal/ent/poststats"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PostStatsCreate is the builder for creating a PostStats entity.
type PostStatsCreate struct {
	config
	mutation *PostStatsMutation
	hooks    []Hook
}

// SetPostID sets the "post_id" field.
func (psc *PostStatsCreate) SetPostID(u uuid.UUID) *PostStatsCreate {
	psc.mutation.SetPostID(u)
	return psc
}

// SetLikeCount sets the "like_count" field.
func (psc *PostStatsCreate) SetLikeCount(i int) *PostStatsCreate {
	psc.mutation.SetLikeCount(i)
	return psc
}

// SetNillableLikeCount sets the "like_count" field if the given value is not nil.
func (psc *PostStatsCreate) SetNillableLikeCount(i *int) *PostStatsCreate {
	if i != nil {
		psc.SetLikeCount(*i)
	}
	return psc
}

// SetReplyCount sets the "reply_count" field.
func (psc *PostStatsCreate) SetReplyCount(i int) *PostStatsCreate {
	psc.mutation.SetReplyCount(i)
	return psc
}

// SetNillableReplyCount sets the "reply_count" field if the given value is not nil.
func (psc *PostStatsCreate) SetNillableReplyCount(i *int) *PostStatsCreate {
	if i != nil {
		psc.SetReplyCount(*i)
	}
	return psc
}

// SetRepostCount sets the "repost_count" field.
func (psc *PostStatsCreate) SetRepostCount(i int) *PostStatsCreate {
	psc.mutation.SetRepostCount(i)
	return psc
}

// SetNillableRepostCount sets the "repost_count" field if the given value is not nil.
func (psc *PostStatsCreate) SetNillableRepostCount(i *int) *PostStatsCreate {
	if i != nil {
		psc.SetRepostCount(*i)
	}
	return psc
}

// SetBookmarkCount sets the "bookmark_count" field.
func (psc *PostStatsCreate) SetBookmarkCount(i int) *PostStatsCreate {
	psc.mutation.SetBookmarkCount(i)
	return psc
}

// SetNillableBookmarkCount sets the "bookmark_count" field if the given value is not nil.
func (psc *PostStatsCreate) SetNillableBookmarkCount(i *int) *PostStatsCreate {
	if i != nil {
		psc.SetBookmarkCount(*i)
	}
	return psc
}

// SetViewCount sets the "view_count" field.
func (psc *PostStatsCreate) SetViewCount(i int) *PostStatsCreate {
	psc.mutation.SetViewCount(i)
	return psc
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (psc *PostStatsCreate) SetNillableViewCount(i *int) *PostStatsCreate {
	if i != nil {
		psc.SetViewCount(*i)
	}
	return psc
}

// SetCreatedAt sets the "created_at" field.
func (psc *PostStatsCreate) SetCreatedAt(t time.Time) *PostStatsCreate {
	psc.mutation.SetCreatedAt(t)
	return psc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (psc *PostStatsCreate) SetNillableCreatedAt(t *time.Time) *PostStatsCreate {
	if t != nil {
		psc.SetCreatedAt(*t)
	}
	return psc
}

// SetUpdatedAt sets the "updated_at" field.
func (psc *PostStatsCreate) SetUpdatedAt(t time.Time) *PostStatsCreate {
	psc.mutation.SetUpdatedAt(t)
	return psc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (psc *PostStatsCreate) SetNillableUpdatedAt(t *time.Time) *PostStatsCreate {
	if t != nil {
		psc.SetUpdatedAt(*t)
	}
	return psc
}

// SetID sets the "id" field.
func (psc *PostStatsCreate) SetID(u uuid.UUID) *PostStatsCreate {
	psc.mutation.SetID(u)
	return psc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (psc *PostStatsCreate) SetNillableID(u *uuid.UUID) *PostStatsCreate {
	if u != nil {
		psc.SetID(*u)
	}
	return psc
}

// Mutation returns the PostStatsMutation object of the builder.
func (psc *PostStatsCreate) Mutation() *PostStatsMutation {
	return psc.mutation
}

// Save creates the PostStats in the database.
func (psc *PostStatsCreate) Save(ctx context.Context) (*PostStats, error) {
	psc.defaults()
	return withHooks(ctx, psc.sqlSave, psc.mutation, psc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (psc *PostStatsCreate) SaveX(ctx context.Context) *PostStats {
	v, err := psc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (psc *PostStatsCreate) Exec(ctx context.Context) error {
	_, err := psc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (psc *PostStatsCreate) ExecX(ctx context.Context) {
	if err := psc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (psc *PostStatsCreate) defaults() {
	if _, ok := psc.mutation.LikeCount(); !ok {
		v := poststats.DefaultLikeCount
		psc.mutation.SetLikeCount(v)
	}
	if _, ok := psc.mutation.ReplyCount(); !ok {
		v := poststats.DefaultReplyCount
		psc.mutation.SetReplyCount(v)
	}
	if _, ok := psc.mutation.RepostCount(); !ok {
		v := poststats.DefaultRepostCount
		psc.mutation.SetRepostCount(v)
	}
	if _, ok := psc.mutation.BookmarkCount(); !ok {
		v := poststats.DefaultBookmarkCount
		psc.mutation.SetBookmarkCount(v)
	}
	if _, ok := psc.mutation.ViewCount(); !ok {
		v := poststats.DefaultViewCount
		psc.mutation.SetViewCount(v)
	}
	if _, ok := psc.mutation.CreatedAt(); !ok {
		v := poststats.DefaultCreatedAt()
		psc.mutation.SetCreatedAt(v)
	}
	if _, ok := psc.mutation.UpdatedAt(); !ok {
		v := poststats.DefaultUpdatedAt()
		psc.mutation.SetUpdatedAt(v)
	}
	if _, ok := psc.mutation.ID(); !ok {
		v := poststats.DefaultID()
		psc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (psc *PostStatsCreate) check() error {
	if _, ok := psc.mutation.PostID(); !ok {
		return &ValidationError{Name: "post_id", err: errors.New(`ent: missing required field "PostStats.post_id"`)}
	}
	if _, ok := psc.mutation.LikeCount(); !ok {
		return &ValidationError{Name: "like_count", err: errors.New(`ent: missing required field "PostStats.like_count"`)}
	}
	if _, ok := psc.mutation.ReplyCount(); !ok {
		return &ValidationError{Name: "reply_count", err: errors.New(`ent: missing required field "PostStats.reply_count"`)}
	}
	if _, ok := psc.mutation.RepostCount(); !ok {
		return &ValidationError{Name: "repost_count", err: errors.New(`ent: missing required field "PostStats.repost_count"`)}
	}
	if _, ok := psc.mutation.BookmarkCount(); !ok {
		return &ValidationError{Name: "bookmark_count", err: errors.New(`ent: missing required field "PostStats.bookmark_count"`)}
	}
	if _, ok := psc.mutation.ViewCount(); !ok {
		return &ValidationError{Name: "view_count", err: errors.New(`ent: missing required field "PostStats.view_count"`)}
	}
	if _, ok := psc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PostStats.created_at"`)}
	}
	if _, ok := psc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PostStats.updated_at"`)}
	}
	return nil
}

func (psc *PostStatsCreate) sqlSave(ctx context.Context) (*PostStats, error) {
	if err := psc.check(); err != nil {
		return nil, err
	}
	_node, _spec := psc.createSpec()
	if err := sqlgraph.CreateNode(ctx, psc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	psc.mutation.id = &_node.ID
	psc.mutation.done = true
	return _node, nil
}

func (psc *PostStatsCreate) createSpec() (*PostStats, *sqlgraph.CreateSpec) {
	var (
		_node = &PostStats{config: psc.config}
		_spec = sqlgraph.NewCreateSpec(poststats.Table, sqlgraph.NewFieldSpec(poststats.FieldID, field.TypeUUID))
	)
	if id, ok := psc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := psc.mutation.PostID(); ok {
		_spec.SetField(poststats.FieldPostID, field.TypeUUID, value)
		_node.PostID = value
	}
	if value, ok := psc.mutation.LikeCount(); ok {
		_spec.SetField(poststats.FieldLikeCount, field.TypeInt, value)
		_node.LikeCount = value
	}
	if value, ok := psc.mutation.ReplyCount(); ok {
		_spec.SetField(poststats.FieldReplyCount, field.TypeInt, value)
		_node.ReplyCount = value
	}
	if value, ok := psc.mutation.RepostCount(); ok {
		_spec.SetField(poststats.FieldRepostCount, field.TypeInt, value)
		_node.RepostCount = value
	}
	if value, ok := psc.mutation.BookmarkCount(); ok {
		_spec.SetField(poststats.FieldBookmarkCount, field.TypeInt, value)
		_node.BookmarkCount = value
	}
	if value, ok := psc.mutation.ViewCount(); ok {
		_spec.SetField(poststats.FieldViewCount, field.TypeInt, value)
		_node.ViewCount = value
	}
	if value, ok := psc.mutation.CreatedAt(); ok {
		_spec.SetField(poststats.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := psc.mutation.UpdatedAt(); ok {
		_spec.SetField(poststats.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// PostStatsCreateBulk is the builder for creating many PostStats entities in bulk.
type PostStatsCreateBulk struct {
	config
	err      error
	builders []*PostStatsCreate
}

// Save creates the PostStats entities in the database.
func (pscb *PostStatsCreateBulk) Save(ctx context.Context) ([]*PostStats, error) {
	if pscb.err != nil {
		return nil, pscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pscb.builders))
	nodes := make([]*PostStats, len(pscb.builders))
	mutators := make([]Mutator, len(pscb.builders))
	for i := range pscb.builders {
		func(i int, root context.Context) {
			builder := pscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PostStatsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pscb *PostStatsCreateBulk) SaveX(ctx context.Context) []*PostStats {
	v, err := pscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pscb *PostStatsCreateBulk) Exec(ctx context.Context) error {
	_, err := pscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pscb *PostStatsCreateBulk) ExecX(ctx context.Context) {
	if err := pscb.Exec(ctx); err != nil {
		panic(err)
	}
}
