// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"social-server/internal/ent/postmedia"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// PostMedia is the model entity for the PostMedia schema.
type PostMedia struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// PostID holds the value of the "post_id" field.
	PostID uuid.UUID `json:"post_id,omitempty"`
	// MediaAssetID holds the value of the "media_asset_id" field.
	MediaAssetID uuid.UUID `json:"media_asset_id,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PostMedia) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case postmedia.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case postmedia.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case postmedia.FieldID, postmedia.FieldPostID, postmedia.FieldMediaAssetID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PostMedia fields.
func (pm *PostMedia) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case postmedia.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				pm.ID = *value
			}
		case postmedia.FieldPostID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field post_id", values[i])
			} else if value != nil {
				pm.PostID = *value
			}
		case postmedia.FieldMediaAssetID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field media_asset_id", values[i])
			} else if value != nil {
				pm.MediaAssetID = *value
			}
		case postmedia.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				pm.SortOrder = int(value.Int64)
			}
		case postmedia.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				pm.CreatedAt = value.Time
			}
		default:
			pm.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PostMedia.
// This includes values selected through modifiers, order, etc.
func (pm *PostMedia) Value(name string) (ent.Value, error) {
	return pm.selectValues.Get(name)
}

// Update returns a builder for updating this PostMedia.
// Note that you need to call PostMedia.Unwrap() before calling this method if this PostMedia
// was returned from a transaction, and the transaction was committed or rolled back.
func (pm *PostMedia) Update() *PostMediaUpdateOne {
	return NewPostMediaClient(pm.config).UpdateOne(pm)
}

// Unwrap unwraps the PostMedia entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pm *PostMedia) Unwrap() *PostMedia {
	_tx, ok := pm.config.driver.(*txDriver)
	if !ok {
		panic("ent: PostMedia is not a transactional entity")
	}
	pm.config.driver = _tx.drv
	return pm
}

// String implements the fmt.Stringer.
func (pm *PostMedia) String() string {
	var builder strings.Builder
	builder.WriteString("PostMedia(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pm.ID))
	builder.WriteString("post_id=")
	builder.WriteString(fmt.Sprintf("%v", pm.PostID))
	builder.WriteString(", ")
	builder.WriteString("media_asset_id=")
	builder.WriteString(fmt.Sprintf("%v", pm.MediaAssetID))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", pm.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(pm.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PostMediaSlice is a parsable slice of PostMedia.
type PostMediaSlice []*PostMedia
