// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"social-server/internal/ent/predicate"
	"social-server/internal/ent/processedevent"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ProcessedEventUpdate is the builder for updating ProcessedEvent entities.
type ProcessedEventUpdate struct {
	config
	hooks    []Hook
	mutation *ProcessedEventMutation
}

// Where appends a list predicates to the ProcessedEventUpdate builder.
func (_u *ProcessedEventUpdate) Where(ps ...predicate.ProcessedEvent) *ProcessedEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEventID sets the "event_id" field.
func (_u *ProcessedEventUpdate) SetEventID(v uuid.UUID) *ProcessedEventUpdate {
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *ProcessedEventUpdate) SetNillableEventID(v *uuid.UUID) *ProcessedEventUpdate {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *ProcessedEventUpdate) SetEventType(v string) *ProcessedEventUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *ProcessedEventUpdate) SetNillableEventType(v *string) *ProcessedEventUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetConsumerGroup sets the "consumer_group" field.
func (_u *ProcessedEventUpdate) SetConsumerGroup(v string) *ProcessedEventUpdate {
	_u.mutation.SetConsumerGroup(v)
	return _u
}

// SetNillableConsumerGroup sets the "consumer_group" field if the given value is not nil.
func (_u *ProcessedEventUpdate) SetNillableConsumerGroup(v *string) *ProcessedEventUpdate {
	if v != nil {
		_u.SetConsumerGroup(*v)
	}
	return _u
}

// Mutation returns the ProcessedEventMutation object of the builder.
func (_u *ProcessedEventUpdate) Mutation() *ProcessedEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProcessedEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProcessedEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProcessedEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProcessedEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProcessedEventUpdate) check() error {
	if v, ok := _u.mutation.EventType(); ok {
		if err := processedevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "ProcessedEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConsumerGroup(); ok {
		if err := processedevent.ConsumerGroupValidator(v); err != nil {
			return &ValidationError{Name: "consumer_group", err: fmt.Errorf(`ent: validator failed for field "ProcessedEvent.consumer_group": %w`, err)}
		}
	}
	return nil
}

func (_u *ProcessedEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(processedevent.Table, processedevent.Columns, sqlgraph.NewFieldSpec(processedevent.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventID(); ok {
		_spec.SetField(processedevent.FieldEventID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(processedevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConsumerGroup(); ok {
		_spec.SetField(processedevent.FieldConsumerGroup, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{processedevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProcessedEventUpdateOne is the builder for updating a single ProcessedEvent entity.
type ProcessedEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProcessedEventMutation
}

// SetEventID sets the "event_id" field.
func (_u *ProcessedEventUpdateOne) SetEventID(v uuid.UUID) *ProcessedEventUpdateOne {
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *ProcessedEventUpdateOne) SetNillableEventID(v *uuid.UUID) *ProcessedEventUpdateOne {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *ProcessedEventUpdateOne) SetEventType(v string) *ProcessedEventUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *ProcessedEventUpdateOne) SetNillableEventType(v *string) *ProcessedEventUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetConsumerGroup sets the "consumer_group" field.
func (_u *ProcessedEventUpdateOne) SetConsumerGroup(v string) *ProcessedEventUpdateOne {
	_u.mutation.SetConsumerGroup(v)
	return _u
}

// SetNillableConsumerGroup sets the "consumer_group" field if the given value is not nil.
func (_u *ProcessedEventUpdateOne) SetNillableConsumerGroup(v *string) *ProcessedEventUpdateOne {
	if v != nil {
		_u.SetConsumerGroup(*v)
	}
	return _u
}

// Mutation returns the ProcessedEventMutation object of the builder.
func (_u *ProcessedEventUpdateOne) Mutation() *ProcessedEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProcessedEventUpdate builder.
func (_u *ProcessedEventUpdateOne) Where(ps ...predicate.ProcessedEvent) *ProcessedEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProcessedEventUpdateOne) Select(field string, fields ...string) *ProcessedEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProcessedEvent entity.
func (_u *ProcessedEventUpdateOne) Save(ctx context.Context) (*ProcessedEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProcessedEventUpdateOne) SaveX(ctx context.Context) *ProcessedEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProcessedEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProcessedEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProcessedEventUpdateOne) check() error {
	if v, ok := _u.mutation.EventType(); ok {
		if err := processedevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "ProcessedEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConsumerGroup(); ok {
		if err := processedevent.ConsumerGroupValidator(v); err != nil {
			return &ValidationError{Name: "consumer_group", err: fmt.Errorf(`ent: validator failed for field "ProcessedEvent.consumer_group": %w`, err)}
		}
	}
	return nil
}

func (_u *ProcessedEventUpdateOne) sqlSave(ctx context.Context) (_node *ProcessedEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(processedevent.Table, processedevent.Columns, sqlgraph.NewFieldSpec(processedevent.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProcessedEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, processedevent.FieldID)
		for _, f := range fields {
			if !processedevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != processedevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventID(); ok {
		_spec.SetField(processedevent.FieldEventID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(processedevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConsumerGroup(); ok {
		_spec.SetField(processedevent.FieldConsumerGroup, field.TypeString, value)
	}
	_node = &ProcessedEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{processedevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
