// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"social-server/internal/ent/processedevent"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ProcessedEventCreate is the builder for creating a ProcessedEvent entity.
type ProcessedEventCreate struct {
	config
	mutation *ProcessedEventMutation
	hooks    []Hook
}

// SetEventID sets the "event_id" field.
func (_c *ProcessedEventCreate) SetEventID(v uuid.UUID) *ProcessedEventCreate {
	_c.mutation.SetEventID(v)
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *ProcessedEventCreate) SetEventType(v string) *ProcessedEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetConsumerGroup sets the "consumer_group" field.
func (_c *ProcessedEventCreate) SetConsumerGroup(v string) *ProcessedEventCreate {
	_c.mutation.SetConsumerGroup(v)
	return _c
}

// SetProcessedAt sets the "processed_at" field.
func (_c *ProcessedEventCreate) SetProcessedAt(v time.Time) *ProcessedEventCreate {
	_c.mutation.SetProcessedAt(v)
	return _c
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (_c *ProcessedEventCreate) SetNillableProcessedAt(v *time.Time) *ProcessedEventCreate {
	if v != nil {
		_c.SetProcessedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProcessedEventCreate) SetCreatedAt(v time.Time) *ProcessedEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProcessedEventCreate) SetNillableCreatedAt(v *time.Time) *ProcessedEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProcessedEventCreate) SetID(v uuid.UUID) *ProcessedEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ProcessedEventCreate) SetNillableID(v *uuid.UUID) *ProcessedEventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ProcessedEventMutation object of the builder.
func (_c *ProcessedEventCreate) Mutation() *ProcessedEventMutation {
	return _c.mutation
}

// Save creates the ProcessedEvent in the database.
func (_c *ProcessedEventCreate) Save(ctx context.Context) (*ProcessedEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProcessedEventCreate) SaveX(ctx context.Context) *ProcessedEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProcessedEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProcessedEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProcessedEventCreate) defaults() {
	if _, ok := _c.mutation.ProcessedAt(); !ok {
		v := processedevent.DefaultProcessedAt()
		_c.mutation.SetProcessedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := processedevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := processedevent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProcessedEventCreate) check() error {
	if _, ok := _c.mutation.EventID(); !ok {
		return &ValidationError{Name: "event_id", err: errors.New(`ent: missing required field "ProcessedEvent.event_id"`)}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "ProcessedEvent.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := processedevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "ProcessedEvent.event_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ConsumerGroup(); !ok {
		return &ValidationError{Name: "consumer_group", err: errors.New(`ent: missing required field "ProcessedEvent.consumer_group"`)}
	}
	if v, ok := _c.mutation.ConsumerGroup(); ok {
		if err := processedevent.ConsumerGroupValidator(v); err != nil {
			return &ValidationError{Name: "consumer_group", err: fmt.Errorf(`ent: validator failed for field "ProcessedEvent.consumer_group": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProcessedAt(); !ok {
		return &ValidationError{Name: "processed_at", err: errors.New(`ent: missing required field "ProcessedEvent.processed_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProcessedEvent.created_at"`)}
	}
	return nil
}

func (_c *ProcessedEventCreate) sqlSave(ctx context.Context) (*ProcessedEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProcessedEventCreate) createSpec() (*ProcessedEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &ProcessedEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(processedevent.Table, sqlgraph.NewFieldSpec(processedevent.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.EventID(); ok {
		_spec.SetField(processedevent.FieldEventID, field.TypeUUID, value)
		_node.EventID = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(processedevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.ConsumerGroup(); ok {
		_spec.SetField(processedevent.FieldConsumerGroup, field.TypeString, value)
		_node.ConsumerGroup = value
	}
	if value, ok := _c.mutation.ProcessedAt(); ok {
		_spec.SetField(processedevent.FieldProcessedAt, field.TypeTime, value)
		_node.ProcessedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(processedevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// ProcessedEventCreateBulk is the builder for creating many ProcessedEvent entities in bulk.
type ProcessedEventCreateBulk struct {
	config
	err      error
	builders []*ProcessedEventCreate
}

// Save creates the ProcessedEvent entities in the database.
func (_c *ProcessedEventCreateBulk) Save(ctx context.Context) ([]*ProcessedEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProcessedEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProcessedEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProcessedEventCreateBulk) SaveX(ctx context.Context) []*ProcessedEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProcessedEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProcessedEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
