// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"social-server/internal/ent/predicate"
	"social-server/internal/ent/processedevent"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProcessedEventDelete is the builder for deleting a ProcessedEvent entity.
type ProcessedEventDelete struct {
	config
	hooks    []Hook
	mutation *ProcessedEventMutation
}

// Where appends a list predicates to the ProcessedEventDelete builder.
func (ped *ProcessedEventDelete) Where(ps ...predicate.ProcessedEvent) *ProcessedEventDelete {
	ped.mutation.Where(ps...)
	return ped
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ped *ProcessedEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ped.sqlExec, ped.mutation, ped.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ped *ProcessedEventDelete) ExecX(ctx context.Context) int {
	n, err := ped.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ped *ProcessedEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(processedevent.Table, sqlgraph.NewFieldSpec(processedevent.FieldID, field.TypeUUID))
	if ps := ped.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ped.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ped.mutation.done = true
	return affected, err
}

// ProcessedEventDeleteOne is the builder for deleting a single ProcessedEvent entity.
type ProcessedEventDeleteOne struct {
	ped *ProcessedEventDelete
}

// Where appends a list predicates to the ProcessedEventDelete builder.
func (pedo *ProcessedEventDeleteOne) Where(ps ...predicate.ProcessedEvent) *ProcessedEventDeleteOne {
	pedo.ped.mutation.Where(ps...)
	return pedo
}

// Exec executes the deletion query.
func (pedo *ProcessedEventDeleteOne) Exec(ctx context.Context) error {
	n, err := pedo.ped.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{processedevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pedo *ProcessedEventDeleteOne) ExecX(ctx context.Context) {
	if err := pedo.Exec(ctx); err != nil {
		panic(err)
	}
}
