// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"social-server/internal/ent/report"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Report is the model entity for the Report schema.
type Report struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ReporterID holds the value of the "reporter_id" field.
	ReporterID uuid.UUID `json:"reporter_id,omitempty"`
	// TargetUserID holds the value of the "target_user_id" field.
	TargetUserID uuid.UUID `json:"target_user_id,omitempty"`
	// TargetPostID holds the value of the "target_post_id" field.
	TargetPostID uuid.UUID `json:"target_post_id,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ReviewNotes holds the value of the "review_notes" field.
	ReviewNotes string `json:"review_notes,omitempty"`
	// ReviewedBy holds the value of the "reviewed_by" field.
	ReviewedBy uuid.UUID `json:"reviewed_by,omitempty"`
	// ReviewedAt holds the value of the "reviewed_at" field.
	ReviewedAt time.Time `json:"reviewed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Report) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case report.FieldType, report.FieldReason, report.FieldStatus, report.FieldReviewNotes:
			values[i] = new(sql.NullString)
		case report.FieldReviewedAt, report.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case report.FieldID, report.FieldReporterID, report.FieldTargetUserID, report.FieldTargetPostID, report.FieldReviewedBy:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Report fields.
func (r *Report) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case report.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				r.ID = *value
			}
		case report.FieldReporterID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field reporter_id", values[i])
			} else if value != nil {
				r.ReporterID = *value
			}
		case report.FieldTargetUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field target_user_id", values[i])
			} else if value != nil {
				r.TargetUserID = *value
			}
		case report.FieldTargetPostID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field target_post_id", values[i])
			} else if value != nil {
				r.TargetPostID = *value
			}
		case report.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				r.Type = value.String
			}
		case report.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				r.Reason = value.String
			}
		case report.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				r.Status = value.String
			}
		case report.FieldReviewNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field review_notes", values[i])
			} else if value.Valid {
				r.ReviewNotes = value.String
			}
		case report.FieldReviewedBy:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_by", values[i])
			} else if value != nil {
				r.ReviewedBy = *value
			}
		case report.FieldReviewedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_at", values[i])
			} else if value.Valid {
				r.ReviewedAt = value.Time
			}
		case report.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				r.CreatedAt = value.Time
			}
		default:
			r.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Report.
// This includes values selected through modifiers, order, etc.
func (r *Report) Value(name string) (ent.Value, error) {
	return r.selectValues.Get(name)
}

// Update returns a builder for updating this Report.
// Note that you need to call Report.Unwrap() before calling this method if this Report
// was returned from a transaction, and the transaction was committed or rolled back.
func (r *Report) Update() *ReportUpdateOne {
	return NewReportClient(r.config).UpdateOne(r)
}

// Unwrap unwraps the Report entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (r *Report) Unwrap() *Report {
	_tx, ok := r.config.driver.(*txDriver)
	if !ok {
		panic("ent: Report is not a transactional entity")
	}
	r.config.driver = _tx.drv
	return r
}

// String implements the fmt.Stringer.
func (r *Report) String() string {
	var builder strings.Builder
	builder.WriteString("Report(")
	builder.WriteString(fmt.Sprintf("id=%v, ", r.ID))
	builder.WriteString("reporter_id=")
	builder.WriteString(fmt.Sprintf("%v", r.ReporterID))
	builder.WriteString(", ")
	builder.WriteString("target_user_id=")
	builder.WriteString(fmt.Sprintf("%v", r.TargetUserID))
	builder.WriteString(", ")
	builder.WriteString("target_post_id=")
	builder.WriteString(fmt.Sprintf("%v", r.TargetPostID))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(r.Type)
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(r.Reason)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(r.Status)
	builder.WriteString(", ")
	builder.WriteString("review_notes=")
	builder.WriteString(r.ReviewNotes)
	builder.WriteString(", ")
	builder.WriteString("reviewed_by=")
	builder.WriteString(fmt.Sprintf("%v", r.ReviewedBy))
	builder.WriteString(", ")
	builder.WriteString("reviewed_at=")
	builder.WriteString(r.ReviewedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(r.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Reports is a parsable slice of Report.
type Reports []*Report
