// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"social-server/internal/ent/predicate"
	"social-server/internal/ent/report"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ReportUpdate is the builder for updating Report entities.
type ReportUpdate struct {
	config
	hooks    []Hook
	mutation *ReportMutation
}

// Where appends a list predicates to the ReportUpdate builder.
func (ru *ReportUpdate) Where(ps ...predicate.Report) *ReportUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetReporterID sets the "reporter_id" field.
func (ru *ReportUpdate) SetReporterID(u uuid.UUID) *ReportUpdate {
	ru.mutation.SetReporterID(u)
	return ru
}

// SetNillableReporterID sets the "reporter_id" field if the given value is not nil.
func (ru *ReportUpdate) SetNillableReporterID(u *uuid.UUID) *ReportUpdate {
	if u != nil {
		ru.SetReporterID(*u)
	}
	return ru
}

// SetTargetUserID sets the "target_user_id" field.
func (ru *ReportUpdate) SetTargetUserID(u uuid.UUID) *ReportUpdate {
	ru.mutation.SetTargetUserID(u)
	return ru
}

// SetNillableTargetUserID sets the "target_user_id" field if the given value is not nil.
func (ru *ReportUpdate) SetNillableTargetUserID(u *uuid.UUID) *ReportUpdate {
	if u != nil {
		ru.SetTargetUserID(*u)
	}
	return ru
}

// ClearTargetUserID clears the value of the "target_user_id" field.
func (ru *ReportUpdate) ClearTargetUserID() *ReportUpdate {
	ru.mutation.ClearTargetUserID()
	return ru
}

// SetTargetPostID sets the "target_post_id" field.
func (ru *ReportUpdate) SetTargetPostID(u uuid.UUID) *ReportUpdate {
	ru.mutation.SetTargetPostID(u)
	return ru
}

// SetNillableTargetPostID sets the "target_post_id" field if the given value is not nil.
func (ru *ReportUpdate) SetNillableTargetPostID(u *uuid.UUID) *ReportUpdate {
	if u != nil {
		ru.SetTargetPostID(*u)
	}
	return ru
}

// ClearTargetPostID clears the value of the "target_post_id" field.
func (ru *ReportUpdate) ClearTargetPostID() *ReportUpdate {
	ru.mutation.ClearTargetPostID()
	return ru
}

// SetType sets the "type" field.
func (ru *ReportUpdate) SetType(s string) *ReportUpdate {
	ru.mutation.SetType(s)
	return ru
}

// SetNillableType sets the "type" field if the given value is not nil.
func (ru *ReportUpdate) SetNillableType(s *string) *ReportUpdate {
	if s != nil {
		ru.SetType(*s)
	}
	return ru
}

// SetReason sets the "reason" field.
func (ru *ReportUpdate) SetReason(s string) *ReportUpdate {
	ru.mutation.SetReason(s)
	return ru
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (ru *ReportUpdate) SetNillableReason(s *string) *ReportUpdate {
	if s != nil {
		ru.SetReason(*s)
	}
	return ru
}

// SetStatus sets the "status" field.
func (ru *ReportUpdate) SetStatus(s string) *ReportUpdate {
	ru.mutation.SetStatus(s)
	return ru
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ru *ReportUpdate) SetNillableStatus(s *string) *ReportUpdate {
	if s != nil {
		ru.SetStatus(*s)
	}
	return ru
}

// SetReviewNotes sets the "review_notes" field.
func (ru *ReportUpdate) SetReviewNotes(s string) *ReportUpdate {
	ru.mutation.SetReviewNotes(s)
	return ru
}

// SetNillableReviewNotes sets the "review_notes" field if the given value is not nil.
func (ru *ReportUpdate) SetNillableReviewNotes(s *string) *ReportUpdate {
	if s != nil {
		ru.SetReviewNotes(*s)
	}
	return ru
}

// SetReviewedBy sets the "reviewed_by" field.
func (ru *ReportUpdate) SetReviewedBy(u uuid.UUID) *ReportUpdate {
	ru.mutation.SetReviewedBy(u)
	return ru
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (ru *ReportUpdate) SetNillableReviewedBy(u *uuid.UUID) *ReportUpdate {
	if u != nil {
		ru.SetReviewedBy(*u)
	}
	return ru
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (ru *ReportUpdate) ClearReviewedBy() *ReportUpdate {
	ru.mutation.ClearReviewedBy()
	return ru
}

// SetReviewedAt sets the "reviewed_at" field.
func (ru *ReportUpdate) SetReviewedAt(t time.Time) *ReportUpdate {
	ru.mutation.SetReviewedAt(t)
	return ru
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (ru *ReportUpdate) SetNillableReviewedAt(t *time.Time) *ReportUpdate {
	if t != nil {
		ru.SetReviewedAt(*t)
	}
	return ru
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (ru *ReportUpdate) ClearReviewedAt() *ReportUpdate {
	ru.mutation.ClearReviewedAt()
	return ru
}

// Mutation returns the ReportMutation object of the builder.
func (ru *ReportUpdate) Mutation() *ReportMutation {
	return ru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *ReportUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *ReportUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *ReportUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *ReportUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ru *ReportUpdate) check() error {
	if v, ok := ru.mutation.GetType(); ok {
		if err := report.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Report.type": %w`, err)}
		}
	}
	if v, ok := ru.mutation.Reason(); ok {
		if err := report.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "Report.reason": %w`, err)}
		}
	}
	return nil
}

func (ru *ReportUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(report.Table, report.Columns, sqlgraph.NewFieldSpec(report.FieldID, field.TypeUUID))
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.ReporterID(); ok {
		_spec.SetField(report.FieldReporterID, field.TypeUUID, value)
	}
	if value, ok := ru.mutation.TargetUserID(); ok {
		_spec.SetField(report.FieldTargetUserID, field.TypeUUID, value)
	}
	if ru.mutation.TargetUserIDCleared() {
		_spec.ClearField(report.FieldTargetUserID, field.TypeUUID)
	}
	if value, ok := ru.mutation.TargetPostID(); ok {
		_spec.SetField(report.FieldTargetPostID, field.TypeUUID, value)
	}
	if ru.mutation.TargetPostIDCleared() {
		_spec.ClearField(report.FieldTargetPostID, field.TypeUUID)
	}
	if value, ok := ru.mutation.GetType(); ok {
		_spec.SetField(report.FieldType, field.TypeString, value)
	}
	if value, ok := ru.mutation.Reason(); ok {
		_spec.SetField(report.FieldReason, field.TypeString, value)
	}
	if value, ok := ru.mutation.Status(); ok {
		_spec.SetField(report.FieldStatus, field.TypeString, value)
	}
	if value, ok := ru.mutation.ReviewNotes(); ok {
		_spec.SetField(report.FieldReviewNotes, field.TypeString, value)
	}
	if value, ok := ru.mutation.ReviewedBy(); ok {
		_spec.SetField(report.FieldReviewedBy, field.TypeUUID, value)
	}
	if ru.mutation.ReviewedByCleared() {
		_spec.ClearField(report.FieldReviewedBy, field.TypeUUID)
	}
	if value, ok := ru.mutation.ReviewedAt(); ok {
		_spec.SetField(report.FieldReviewedAt, field.TypeTime, value)
	}
	if ru.mutation.ReviewedAtCleared() {
		_spec.ClearField(report.FieldReviewedAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{report.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// ReportUpdateOne is the builder for updating a single Report entity.
type ReportUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReportMutation
}

// SetReporterID sets the "reporter_id" field.
func (ruo *ReportUpdateOne) SetReporterID(u uuid.UUID) *ReportUpdateOne {
	ruo.mutation.SetReporterID(u)
	return ruo
}

// SetNillableReporterID sets the "reporter_id" field if the given value is not nil.
func (ruo *ReportUpdateOne) SetNillableReporterID(u *uuid.UUID) *ReportUpdateOne {
	if u != nil {
		ruo.SetReporterID(*u)
	}
	return ruo
}

// SetTargetUserID sets the "target_user_id" field.
func (ruo *ReportUpdateOne) SetTargetUserID(u uuid.UUID) *ReportUpdateOne {
	ruo.mutation.SetTargetUserID(u)
	return ruo
}

// SetNillableTargetUserID sets the "target_user_id" field if the given value is not nil.
func (ruo *ReportUpdateOne) SetNillableTargetUserID(u *uuid.UUID) *ReportUpdateOne {
	if u != nil {
		ruo.SetTargetUserID(*u)
	}
	return ruo
}

// ClearTargetUserID clears the value of the "target_user_id" field.
func (ruo *ReportUpdateOne) ClearTargetUserID() *ReportUpdateOne {
	ruo.mutation.ClearTargetUserID()
	return ruo
}

// SetTargetPostID sets the "target_post_id" field.
func (ruo *ReportUpdateOne) SetTargetPostID(u uuid.UUID) *ReportUpdateOne {
	ruo.mutation.SetTargetPostID(u)
	return ruo
}

// SetNillableTargetPostID sets the "target_post_id" field if the given value is not nil.
func (ruo *ReportUpdateOne) SetNillableTargetPostID(u *uuid.UUID) *ReportUpdateOne {
	if u != nil {
		ruo.SetTargetPostID(*u)
	}
	return ruo
}

// ClearTargetPostID clears the value of the "target_post_id" field.
func (ruo *ReportUpdateOne) ClearTargetPostID() *ReportUpdateOne {
	ruo.mutation.ClearTargetPostID()
	return ruo
}

// SetType sets the "type" field.
func (ruo *ReportUpdateOne) SetType(s string) *ReportUpdateOne {
	ruo.mutation.SetType(s)
	return ruo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (ruo *ReportUpdateOne) SetNillableType(s *string) *ReportUpdateOne {
	if s != nil {
		ruo.SetType(*s)
	}
	return ruo
}

// SetReason sets the "reason" field.
func (ruo *ReportUpdateOne) SetReason(s string) *ReportUpdateOne {
	ruo.mutation.SetReason(s)
	return ruo
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (ruo *ReportUpdateOne) SetNillableReason(s *string) *ReportUpdateOne {
	if s != nil {
		ruo.SetReason(*s)
	}
	return ruo
}

// SetStatus sets the "status" field.
func (ruo *ReportUpdateOne) SetStatus(s string) *ReportUpdateOne {
	ruo.mutation.SetStatus(s)
	return ruo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ruo *ReportUpdateOne) SetNillableStatus(s *string) *ReportUpdateOne {
	if s != nil {
		ruo.SetStatus(*s)
	}
	return ruo
}

// SetReviewNotes sets the "review_notes" field.
func (ruo *ReportUpdateOne) SetReviewNotes(s string) *ReportUpdateOne {
	ruo.mutation.SetReviewNotes(s)
	return ruo
}

// SetNillableReviewNotes sets the "review_notes" field if the given value is not nil.
func (ruo *ReportUpdateOne) SetNillableReviewNotes(s *string) *ReportUpdateOne {
	if s != nil {
		ruo.SetReviewNotes(*s)
	}
	return ruo
}

// SetReviewedBy sets the "reviewed_by" field.
func (ruo *ReportUpdateOne) SetReviewedBy(u uuid.UUID) *ReportUpdateOne {
	ruo.mutation.SetReviewedBy(u)
	return ruo
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (ruo *ReportUpdateOne) SetNillableReviewedBy(u *uuid.UUID) *ReportUpdateOne {
	if u != nil {
		ruo.SetReviewedBy(*u)
	}
	return ruo
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (ruo *ReportUpdateOne) ClearReviewedBy() *ReportUpdateOne {
	ruo.mutation.ClearReviewedBy()
	return ruo
}

// SetReviewedAt sets the "reviewed_at" field.
func (ruo *ReportUpdateOne) SetReviewedAt(t time.Time) *ReportUpdateOne {
	ruo.mutation.SetReviewedAt(t)
	return ruo
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (ruo *ReportUpdateOne) SetNillableReviewedAt(t *time.Time) *ReportUpdateOne {
	if t != nil {
		ruo.SetReviewedAt(*t)
	}
	return ruo
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (ruo *ReportUpdateOne) ClearReviewedAt() *ReportUpdateOne {
	ruo.mutation.ClearReviewedAt()
	return ruo
}

// Mutation returns the ReportMutation object of the builder.
func (ruo *ReportUpdateOne) Mutation() *ReportMutation {
	return ruo.mutation
}

// Where appends a list predicates to the ReportUpdate builder.
func (ruo *ReportUpdateOne) Where(ps ...predicate.Report) *ReportUpdateOne {
	ruo.mutation.Where(ps...)
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *ReportUpdateOne) Select(field string, fields ...string) *ReportUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Report entity.
func (ruo *ReportUpdateOne) Save(ctx context.Context) (*Report, error) {
	return withHooks(ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *ReportUpdateOne) SaveX(ctx context.Context) *Report {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *ReportUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *ReportUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ruo *ReportUpdateOne) check() error {
	if v, ok := ruo.mutation.GetType(); ok {
		if err := report.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Report.type": %w`, err)}
		}
	}
	if v, ok := ruo.mutation.Reason(); ok {
		if err := report.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "Report.reason": %w`, err)}
		}
	}
	return nil
}

func (ruo *ReportUpdateOne) sqlSave(ctx context.Context) (_node *Report, err error) {
	if err := ruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(report.Table, report.Columns, sqlgraph.NewFieldSpec(report.FieldID, field.TypeUUID))
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Report.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, report.FieldID)
		for _, f := range fields {
			if !report.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != report.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.ReporterID(); ok {
		_spec.SetField(report.FieldReporterID, field.TypeUUID, value)
	}
	if value, ok := ruo.mutation.TargetUserID(); ok {
		_spec.SetField(report.FieldTargetUserID, field.TypeUUID, value)
	}
	if ruo.mutation.TargetUserIDCleared() {
		_spec.ClearField(report.FieldTargetUserID, field.TypeUUID)
	}
	if value, ok := ruo.mutation.TargetPostID(); ok {
		_spec.SetField(report.FieldTargetPostID, field.TypeUUID, value)
	}
	if ruo.mutation.TargetPostIDCleared() {
		_spec.ClearField(report.FieldTargetPostID, field.TypeUUID)
	}
	if value, ok := ruo.mutation.GetType(); ok {
		_spec.SetField(report.FieldType, field.TypeString, value)
	}
	if value, ok := ruo.mutation.Reason(); ok {
		_spec.SetField(report.FieldReason, field.TypeString, value)
	}
	if value, ok := ruo.mutation.Status(); ok {
		_spec.SetField(report.FieldStatus, field.TypeString, value)
	}
	if value, ok := ruo.mutation.ReviewNotes(); ok {
		_spec.SetField(report.FieldReviewNotes, field.TypeString, value)
	}
	if value, ok := ruo.mutation.ReviewedBy(); ok {
		_spec.SetField(report.FieldReviewedBy, field.TypeUUID, value)
	}
	if ruo.mutation.ReviewedByCleared() {
		_spec.ClearField(report.FieldReviewedBy, field.TypeUUID)
	}
	if value, ok := ruo.mutation.ReviewedAt(); ok {
		_spec.SetField(report.FieldReviewedAt, field.TypeTime, value)
	}
	if ruo.mutation.ReviewedAtCleared() {
		_spec.ClearField(report.FieldReviewedAt, field.TypeTime)
	}
	_node = &Report{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{report.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
