// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"social-server/internal/ent/report"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ReportCreate is the builder for creating a Report entity.
type ReportCreate struct {
	config
	mutation *ReportMutation
	hooks    []Hook
}

// SetReporterID sets the "reporter_id" field.
func (rc *ReportCreate) SetReporterID(u uuid.UUID) *ReportCreate {
	rc.mutation.SetReporterID(u)
	return rc
}

// SetTargetUserID sets the "target_user_id" field.
func (rc *ReportCreate) SetTargetUserID(u uuid.UUID) *ReportCreate {
	rc.mutation.SetTargetUserID(u)
	return rc
}

// SetNillableTargetUserID sets the "target_user_id" field if the given value is not nil.
func (rc *ReportCreate) SetNillableTargetUserID(u *uuid.UUID) *ReportCreate {
	if u != nil {
		rc.SetTargetUserID(*u)
	}
	return rc
}

// SetTargetPostID sets the "target_post_id" field.
func (rc *ReportCreate) SetTargetPostID(u uuid.UUID) *ReportCreate {
	rc.mutation.SetTargetPostID(u)
	return rc
}

// SetNillableTargetPostID sets the "target_post_id" field if the given value is not nil.
func (rc *ReportCreate) SetNillableTargetPostID(u *uuid.UUID) *ReportCreate {
	if u != nil {
		rc.SetTargetPostID(*u)
	}
	return rc
}

// SetType sets the "type" field.
func (rc *ReportCreate) SetType(s string) *ReportCreate {
	rc.mutation.SetType(s)
	return rc
}

// SetReason sets the "reason" field.
func (rc *ReportCreate) SetReason(s string) *ReportCreate {
	rc.mutation.SetReason(s)
	return rc
}

// SetStatus sets the "status" field.
func (rc *ReportCreate) SetStatus(s string) *ReportCreate {
	rc.mutation.SetStatus(s)
	return rc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (rc *ReportCreate) SetNillableStatus(s *string) *ReportCreate {
	if s != nil {
		rc.SetStatus(*s)
	}
	return rc
}

// SetReviewNotes sets the "review_notes" field.
func (rc *ReportCreate) SetReviewNotes(s string) *ReportCreate {
	rc.mutation.SetReviewNotes(s)
	return rc
}

// SetNillableReviewNotes sets the "review_notes" field if the given value is not nil.
func (rc *ReportCreate) SetNillableReviewNotes(s *string) *ReportCreate {
	if s != nil {
		rc.SetReviewNotes(*s)
	}
	return rc
}

// SetReviewedBy sets the "reviewed_by" field.
func (rc *ReportCreate) SetReviewedBy(u uuid.UUID) *ReportCreate {
	rc.mutation.SetReviewedBy(u)
	return rc
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (rc *ReportCreate) SetNillableReviewedBy(u *uuid.UUID) *ReportCreate {
	if u != nil {
		rc.SetReviewedBy(*u)
	}
	return rc
}

// SetReviewedAt sets the "reviewed_at" field.
func (rc *ReportCreate) SetReviewedAt(t time.Time) *ReportCreate {
	rc.mutation.SetReviewedAt(t)
	return rc
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (rc *ReportCreate) SetNillableReviewedAt(t *time.Time) *ReportCreate {
	if t != nil {
		rc.SetReviewedAt(*t)
	}
	return rc
}

// SetCreatedAt sets the "created_at" field.
func (rc *ReportCreate) SetCreatedAt(t time.Time) *ReportCreate {
	rc.mutation.SetCreatedAt(t)
	return rc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (rc *ReportCreate) SetNillableCreatedAt(t *time.Time) *ReportCreate {
	if t != nil {
		rc.SetCreatedAt(*t)
	}
	return rc
}

// SetID sets the "id" field.
func (rc *ReportCreate) SetID(u uuid.UUID) *ReportCreate {
	rc.mutation.SetID(u)
	return rc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (rc *ReportCreate) SetNillableID(u *uuid.UUID) *ReportCreate {
	if u != nil {
		rc.SetID(*u)
	}
	return rc
}

// Mutation returns the ReportMutation object of the builder.
func (rc *ReportCreate) Mutation() *ReportMutation {
	return rc.mutation
}

// Save creates the Report in the database.
func (rc *ReportCreate) Save(ctx context.Context) (*Report, error) {
	rc.defaults()
	return withHooks(ctx, rc.sqlSave, rc.mutation, rc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rc *ReportCreate) SaveX(ctx context.Context) *Report {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *ReportCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *ReportCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rc *ReportCreate) defaults() {
	if _, ok := rc.mutation.Status(); !ok {
		v := report.DefaultStatus
		rc.mutation.SetStatus(v)
	}
	if _, ok := rc.mutation.ReviewNotes(); !ok {
		v := report.DefaultReviewNotes
		rc.mutation.SetReviewNotes(v)
	}
	if _, ok := rc.mutation.CreatedAt(); !ok {
		v := report.DefaultCreatedAt()
		rc.mutation.SetCreatedAt(v)
	}
	if _, ok := rc.mutation.ID(); !ok {
		v := report.DefaultID()
		rc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *ReportCreate) check() error {
	if _, ok := rc.mutation.ReporterID(); !ok {
		return &ValidationError{Name: "reporter_id", err: errors.New(`ent: missing required field "Report.reporter_id"`)}
	}
	if _, ok := rc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Report.type"`)}
	}
	if v, ok := rc.mutation.GetType(); ok {
		if err := report.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Report.type": %w`, err)}
		}
	}
	if _, ok := rc.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "Report.reason"`)}
	}
	if v, ok := rc.mutation.Reason(); ok {
		if err := report.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "Report.reason": %w`, err)}
		}
	}
	if _, ok := rc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Report.status"`)}
	}
	if _, ok := rc.mutation.ReviewNotes(); !ok {
		return &ValidationError{Name: "review_notes", err: errors.New(`ent: missing required field "Report.review_notes"`)}
	}
	if _, ok := rc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Report.created_at"`)}
	}
	return nil
}

func (rc *ReportCreate) sqlSave(ctx context.Context) (*Report, error) {
	if err := rc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	rc.mutation.id = &_node.ID
	rc.mutation.done = true
	return _node, nil
}

func (rc *ReportCreate) createSpec() (*Report, *sqlgraph.CreateSpec) {
	var (
		_node = &Report{config: rc.config}
		_spec = sqlgraph.NewCreateSpec(report.Table, sqlgraph.NewFieldSpec(report.FieldID, field.TypeUUID))
	)
	if id, ok := rc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := rc.mutation.ReporterID(); ok {
		_spec.SetField(report.FieldReporterID, field.TypeUUID, value)
		_node.ReporterID = value
	}
	if value, ok := rc.mutation.TargetUserID(); ok {
		_spec.SetField(report.FieldTargetUserID, field.TypeUUID, value)
		_node.TargetUserID = value
	}
	if value, ok := rc.mutation.TargetPostID(); ok {
		_spec.SetField(report.FieldTargetPostID, field.TypeUUID, value)
		_node.TargetPostID = value
	}
	if value, ok := rc.mutation.GetType(); ok {
		_spec.SetField(report.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := rc.mutation.Reason(); ok {
		_spec.SetField(report.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := rc.mutation.Status(); ok {
		_spec.SetField(report.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := rc.mutation.ReviewNotes(); ok {
		_spec.SetField(report.FieldReviewNotes, field.TypeString, value)
		_node.ReviewNotes = value
	}
	if value, ok := rc.mutation.ReviewedBy(); ok {
		_spec.SetField(report.FieldReviewedBy, field.TypeUUID, value)
		_node.ReviewedBy = value
	}
	if value, ok := rc.mutation.ReviewedAt(); ok {
		_spec.SetField(report.FieldReviewedAt, field.TypeTime, value)
		_node.ReviewedAt = value
	}
	if value, ok := rc.mutation.CreatedAt(); ok {
		_spec.SetField(report.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// ReportCreateBulk is the builder for creating many Report entities in bulk.
type ReportCreateBulk struct {
	config
	err      error
	builders []*ReportCreate
}

// Save creates the Report entities in the database.
func (rcb *ReportCreateBulk) Save(ctx context.Context) ([]*Report, error) {
	if rcb.err != nil {
		return nil, rcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Report, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReportMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *ReportCreateBulk) SaveX(ctx context.Context) []*Report {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *ReportCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *ReportCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}
