// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"social-server/internal/ent/predicate"
	"social-server/internal/ent/userstats"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserStatsUpdate is the builder for updating UserStats entities.
type UserStatsUpdate struct {
	config
	hooks    []Hook
	mutation *UserStatsMutation
}

// Where appends a list predicates to the UserStatsUpdate builder.
func (usu *UserStatsUpdate) Where(ps ...predicate.UserStats) *UserStatsUpdate {
	usu.mutation.Where(ps...)
	return usu
}

// SetUserID sets the "user_id" field.
func (usu *UserStatsUpdate) SetUserID(u uuid.UUID) *UserStatsUpdate {
	usu.mutation.SetUserID(u)
	return usu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (usu *UserStatsUpdate) SetNillableUserID(u *uuid.UUID) *UserStatsUpdate {
	if u != nil {
		usu.SetUserID(*u)
	}
	return usu
}

// SetPostCount sets the "post_count" field.
func (usu *UserStatsUpdate) SetPostCount(i int) *UserStatsUpdate {
	usu.mutation.ResetPostCount()
	usu.mutation.SetPostCount(i)
	return usu
}

// SetNillablePostCount sets the "post_count" field if the given value is not nil.
func (usu *UserStatsUpdate) SetNillablePostCount(i *int) *UserStatsUpdate {
	if i != nil {
		usu.SetPostCount(*i)
	}
	return usu
}

// AddPostCount adds i to the "post_count" field.
func (usu *UserStatsUpdate) AddPostCount(i int) *UserStatsUpdate {
	usu.mutation.AddPostCount(i)
	return usu
}

// SetFollowerCount sets the "follower_count" field.
func (usu *UserStatsUpdate) SetFollowerCount(i int) *UserStatsUpdate {
	usu.mutation.ResetFollowerCount()
	usu.mutation.SetFollowerCount(i)
	return usu
}

// SetNillableFollowerCount sets the "follower_count" field if the given value is not nil.
func (usu *UserStatsUpdate) SetNillableFollowerCount(i *int) *UserStatsUpdate {
	if i != nil {
		usu.SetFollowerCount(*i)
	}
	return usu
}

// AddFollowerCount adds i to the "follower_count" field.
func (usu *UserStatsUpdate) AddFollowerCount(i int) *UserStatsUpdate {
	usu.mutation.AddFollowerCount(i)
	return usu
}

// SetFollowingCount sets the "following_count" field.
func (usu *UserStatsUpdate) SetFollowingCount(i int) *UserStatsUpdate {
	usu.mutation.ResetFollowingCount()
	usu.mutation.SetFollowingCount(i)
	return usu
}

// SetNillableFollowingCount sets the "following_count" field if the given value is not nil.
func (usu *UserStatsUpdate) SetNillableFollowingCount(i *int) *UserStatsUpdate {
	if i != nil {
		usu.SetFollowingCount(*i)
	}
	return usu
}

// AddFollowingCount adds i to the "following_count" field.
func (usu *UserStatsUpdate) AddFollowingCount(i int) *UserStatsUpdate {
	usu.mutation.AddFollowingCount(i)
	return usu
}

// SetLikeReceivedCount sets the "like_received_count" field.
func (usu *UserStatsUpdate) SetLikeReceivedCount(i int) *UserStatsUpdate {
	usu.mutation.ResetLikeReceivedCount()
	usu.mutation.SetLikeReceivedCount(i)
	return usu
}

// SetNillableLikeReceivedCount sets the "like_received_count" field if the given value is not nil.
func (usu *UserStatsUpdate) SetNillableLikeReceivedCount(i *int) *UserStatsUpdate {
	if i != nil {
		usu.SetLikeReceivedCount(*i)
	}
	return usu
}

// AddLikeReceivedCount adds i to the "like_received_count" field.
func (usu *UserStatsUpdate) AddLikeReceivedCount(i int) *UserStatsUpdate {
	usu.mutation.AddLikeReceivedCount(i)
	return usu
}

// Mutation returns the UserStatsMutation object of the builder.
func (usu *UserStatsUpdate) Mutation() *UserStatsMutation {
	return usu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (usu *UserStatsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, usu.sqlSave, usu.mutation, usu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (usu *UserStatsUpdate) SaveX(ctx context.Context) int {
	affected, err := usu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (usu *UserStatsUpdate) Exec(ctx context.Context) error {
	_, err := usu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (usu *UserStatsUpdate) ExecX(ctx context.Context) {
	if err := usu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (usu *UserStatsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(userstats.Table, userstats.Columns, sqlgraph.NewFieldSpec(userstats.FieldID, field.TypeUUID))
	if ps := usu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := usu.mutation.UserID(); ok {
		_spec.SetField(userstats.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := usu.mutation.PostCount(); ok {
		_spec.SetField(userstats.FieldPostCount, field.TypeInt, value)
	}
	if value, ok := usu.mutation.AddedPostCount(); ok {
		_spec.AddField(userstats.FieldPostCount, field.TypeInt, value)
	}
	if value, ok := usu.mutation.FollowerCount(); ok {
		_spec.SetField(userstats.FieldFollowerCount, field.TypeInt, value)
	}
	if value, ok := usu.mutation.AddedFollowerCount(); ok {
		_spec.AddField(userstats.FieldFollowerCount, field.TypeInt, value)
	}
	if value, ok := usu.mutation.FollowingCount(); ok {
		_spec.SetField(userstats.FieldFollowingCount, field.TypeInt, value)
	}
	if value, ok := usu.mutation.AddedFollowingCount(); ok {
		_spec.AddField(userstats.FieldFollowingCount, field.TypeInt, value)
	}
	if value, ok := usu.mutation.LikeReceivedCount(); ok {
		_spec.SetField(userstats.FieldLikeReceivedCount, field.TypeInt, value)
	}
	if value, ok := usu.mutation.AddedLikeReceivedCount(); ok {
		_spec.AddField(userstats.FieldLikeReceivedCount, field.TypeInt, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, usu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userstats.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	usu.mutation.done = true
	return n, nil
}

// UserStatsUpdateOne is the builder for updating a single UserStats entity.
type UserStatsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserStatsMutation
}

// SetUserID sets the "user_id" field.
func (usuo *UserStatsUpdateOne) SetUserID(u uuid.UUID) *UserStatsUpdateOne {
	usuo.mutation.SetUserID(u)
	return usuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (usuo *UserStatsUpdateOne) SetNillableUserID(u *uuid.UUID) *UserStatsUpdateOne {
	if u != nil {
		usuo.SetUserID(*u)
	}
	return usuo
}

// SetPostCount sets the "post_count" field.
func (usuo *UserStatsUpdateOne) SetPostCount(i int) *UserStatsUpdateOne {
	usuo.mutation.ResetPostCount()
	usuo.mutation.SetPostCount(i)
	return usuo
}

// SetNillablePostCount sets the "post_count" field if the given value is not nil.
func (usuo *UserStatsUpdateOne) SetNillablePostCount(i *int) *UserStatsUpdateOne {
	if i != nil {
		usuo.SetPostCount(*i)
	}
	return usuo
}

// AddPostCount adds i to the "post_count" field.
func (usuo *UserStatsUpdateOne) AddPostCount(i int) *UserStatsUpdateOne {
	usuo.mutation.AddPostCount(i)
	return usuo
}

// SetFollowerCount sets the "follower_count" field.
func (usuo *UserStatsUpdateOne) SetFollowerCount(i int) *UserStatsUpdateOne {
	usuo.mutation.ResetFollowerCount()
	usuo.mutation.SetFollowerCount(i)
	return usuo
}

// SetNillableFollowerCount sets the "follower_count" field if the given value is not nil.
func (usuo *UserStatsUpdateOne) SetNillableFollowerCount(i *int) *UserStatsUpdateOne {
	if i != nil {
		usuo.SetFollowerCount(*i)
	}
	return usuo
}

// AddFollowerCount adds i to the "follower_count" field.
func (usuo *UserStatsUpdateOne) AddFollowerCount(i int) *UserStatsUpdateOne {
	usuo.mutation.AddFollowerCount(i)
	return usuo
}

// SetFollowingCount sets the "following_count" field.
func (usuo *UserStatsUpdateOne) SetFollowingCount(i int) *UserStatsUpdateOne {
	usuo.mutation.ResetFollowingCount()
	usuo.mutation.SetFollowingCount(i)
	return usuo
}

// SetNillableFollowingCount sets the "following_count" field if the given value is not nil.
func (usuo *UserStatsUpdateOne) SetNillableFollowingCount(i *int) *UserStatsUpdateOne {
	if i != nil {
		usuo.SetFollowingCount(*i)
	}
	return usuo
}

// AddFollowingCount adds i to the "following_count" field.
func (usuo *UserStatsUpdateOne) AddFollowingCount(i int) *UserStatsUpdateOne {
	usuo.mutation.AddFollowingCount(i)
	return usuo
}

// SetLikeReceivedCount sets the "like_received_count" field.
func (usuo *UserStatsUpdateOne) SetLikeReceivedCount(i int) *UserStatsUpdateOne {
	usuo.mutation.ResetLikeReceivedCount()
	usuo.mutation.SetLikeReceivedCount(i)
	return usuo
}

// SetNillableLikeReceivedCount sets the "like_received_count" field if the given value is not nil.
func (usuo *UserStatsUpdateOne) SetNillableLikeReceivedCount(i *int) *UserStatsUpdateOne {
	if i != nil {
		usuo.SetLikeReceivedCount(*i)
	}
	return usuo
}

// AddLikeReceivedCount adds i to the "like_received_count" field.
func (usuo *UserStatsUpdateOne) AddLikeReceivedCount(i int) *UserStatsUpdateOne {
	usuo.mutation.AddLikeReceivedCount(i)
	return usuo
}

// Mutation returns the UserStatsMutation object of the builder.
func (usuo *UserStatsUpdateOne) Mutation() *UserStatsMutation {
	return usuo.mutation
}

// Where appends a list predicates to the UserStatsUpdate builder.
func (usuo *UserStatsUpdateOne) Where(ps ...predicate.UserStats) *UserStatsUpdateOne {
	usuo.mutation.Where(ps...)
	return usuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (usuo *UserStatsUpdateOne) Select(field string, fields ...string) *UserStatsUpdateOne {
	usuo.fields = append([]string{field}, fields...)
	return usuo
}

// Save executes the query and returns the updated UserStats entity.
func (usuo *UserStatsUpdateOne) Save(ctx context.Context) (*UserStats, error) {
	return withHooks(ctx, usuo.sqlSave, usuo.mutation, usuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (usuo *UserStatsUpdateOne) SaveX(ctx context.Context) *UserStats {
	node, err := usuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (usuo *UserStatsUpdateOne) Exec(ctx context.Context) error {
	_, err := usuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (usuo *UserStatsUpdateOne) ExecX(ctx context.Context) {
	if err := usuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (usuo *UserStatsUpdateOne) sqlSave(ctx context.Context) (_node *UserStats, err error) {
	_spec := sqlgraph.NewUpdateSpec(userstats.Table, userstats.Columns, sqlgraph.NewFieldSpec(userstats.FieldID, field.TypeUUID))
	id, ok := usuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserStats.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := usuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userstats.FieldID)
		for _, f := range fields {
			if !userstats.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userstats.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := usuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := usuo.mutation.UserID(); ok {
		_spec.SetField(userstats.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := usuo.mutation.PostCount(); ok {
		_spec.SetField(userstats.FieldPostCount, field.TypeInt, value)
	}
	if value, ok := usuo.mutation.AddedPostCount(); ok {
		_spec.AddField(userstats.FieldPostCount, field.TypeInt, value)
	}
	if value, ok := usuo.mutation.FollowerCount(); ok {
		_spec.SetField(userstats.FieldFollowerCount, field.TypeInt, value)
	}
	if value, ok := usuo.mutation.AddedFollowerCount(); ok {
		_spec.AddField(userstats.FieldFollowerCount, field.TypeInt, value)
	}
	if value, ok := usuo.mutation.FollowingCount(); ok {
		_spec.SetField(userstats.FieldFollowingCount, field.TypeInt, value)
	}
	if value, ok := usuo.mutation.AddedFollowingCount(); ok {
		_spec.AddField(userstats.FieldFollowingCount, field.TypeInt, value)
	}
	if value, ok := usuo.mutation.LikeReceivedCount(); ok {
		_spec.SetField(userstats.FieldLikeReceivedCount, field.TypeInt, value)
	}
	if value, ok := usuo.mutation.AddedLikeReceivedCount(); ok {
		_spec.AddField(userstats.FieldLikeReceivedCount, field.TypeInt, value)
	}
	_node = &UserStats{config: usuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, usuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userstats.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	usuo.mutation.done = true
	return _node, nil
}
