// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"social-server/internal/ent/userstats"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserStatsCreate is the builder for creating a UserStats entity.
type UserStatsCreate struct {
	config
	mutation *UserStatsMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (usc *UserStatsCreate) SetUserID(u uuid.UUID) *UserStatsCreate {
	usc.mutation.SetUserID(u)
	return usc
}

// SetPostCount sets the "post_count" field.
func (usc *UserStatsCreate) SetPostCount(i int) *UserStatsCreate {
	usc.mutation.SetPostCount(i)
	return usc
}

// SetNillablePostCount sets the "post_count" field if the given value is not nil.
func (usc *UserStatsCreate) SetNillablePostCount(i *int) *UserStatsCreate {
	if i != nil {
		usc.SetPostCount(*i)
	}
	return usc
}

// SetFollowerCount sets the "follower_count" field.
func (usc *UserStatsCreate) SetFollowerCount(i int) *UserStatsCreate {
	usc.mutation.SetFollowerCount(i)
	return usc
}

// SetNillableFollowerCount sets the "follower_count" field if the given value is not nil.
func (usc *UserStatsCreate) SetNillableFollowerCount(i *int) *UserStatsCreate {
	if i != nil {
		usc.SetFollowerCount(*i)
	}
	return usc
}

// SetFollowingCount sets the "following_count" field.
func (usc *UserStatsCreate) SetFollowingCount(i int) *UserStatsCreate {
	usc.mutation.SetFollowingCount(i)
	return usc
}

// SetNillableFollowingCount sets the "following_count" field if the given value is not nil.
func (usc *UserStatsCreate) SetNillableFollowingCount(i *int) *UserStatsCreate {
	if i != nil {
		usc.SetFollowingCount(*i)
	}
	return usc
}

// SetLikeReceivedCount sets the "like_received_count" field.
func (usc *UserStatsCreate) SetLikeReceivedCount(i int) *UserStatsCreate {
	usc.mutation.SetLikeReceivedCount(i)
	return usc
}

// SetNillableLikeReceivedCount sets the "like_received_count" field if the given value is not nil.
func (usc *UserStatsCreate) SetNillableLikeReceivedCount(i *int) *UserStatsCreate {
	if i != nil {
		usc.SetLikeReceivedCount(*i)
	}
	return usc
}

// SetCreatedAt sets the "created_at" field.
func (usc *UserStatsCreate) SetCreatedAt(t time.Time) *UserStatsCreate {
	usc.mutation.SetCreatedAt(t)
	return usc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (usc *UserStatsCreate) SetNillableCreatedAt(t *time.Time) *UserStatsCreate {
	if t != nil {
		usc.SetCreatedAt(*t)
	}
	return usc
}

// SetUpdatedAt sets the "updated_at" field.
func (usc *UserStatsCreate) SetUpdatedAt(t time.Time) *UserStatsCreate {
	usc.mutation.SetUpdatedAt(t)
	return usc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (usc *UserStatsCreate) SetNillableUpdatedAt(t *time.Time) *UserStatsCreate {
	if t != nil {
		usc.SetUpdatedAt(*t)
	}
	return usc
}

// SetID sets the "id" field.
func (usc *UserStatsCreate) SetID(u uuid.UUID) *UserStatsCreate {
	usc.mutation.SetID(u)
	return usc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (usc *UserStatsCreate) SetNillableID(u *uuid.UUID) *UserStatsCreate {
	if u != nil {
		usc.SetID(*u)
	}
	return usc
}

// Mutation returns the UserStatsMutation object of the builder.
func (usc *UserStatsCreate) Mutation() *UserStatsMutation {
	return usc.mutation
}

// Save creates the UserStats in the database.
func (usc *UserStatsCreate) Save(ctx context.Context) (*UserStats, error) {
	usc.defaults()
	return withHooks(ctx, usc.sqlSave, usc.mutation, usc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (usc *UserStatsCreate) SaveX(ctx context.Context) *UserStats {
	v, err := usc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (usc *UserStatsCreate) Exec(ctx context.Context) error {
	_, err := usc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (usc *UserStatsCreate) ExecX(ctx context.Context) {
	if err := usc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (usc *UserStatsCreate) defaults() {
	if _, ok := usc.mutation.PostCount(); !ok {
		v := userstats.DefaultPostCount
		usc.mutation.SetPostCount(v)
	}
	if _, ok := usc.mutation.FollowerCount(); !ok {
		v := userstats.DefaultFollowerCount
		usc.mutation.SetFollowerCount(v)
	}
	if _, ok := usc.mutation.FollowingCount(); !ok {
		v := userstats.DefaultFollowingCount
		usc.mutation.SetFollowingCount(v)
	}
	if _, ok := usc.mutation.LikeReceivedCount(); !ok {
		v := userstats.DefaultLikeReceivedCount
		usc.mutation.SetLikeReceivedCount(v)
	}
	if _, ok := usc.mutation.CreatedAt(); !ok {
		v := userstats.DefaultCreatedAt()
		usc.mutation.SetCreatedAt(v)
	}
	if _, ok := usc.mutation.UpdatedAt(); !ok {
		v := userstats.DefaultUpdatedAt()
		usc.mutation.SetUpdatedAt(v)
	}
	if _, ok := usc.mutation.ID(); !ok {
		v := userstats.DefaultID()
		usc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (usc *UserStatsCreate) check() error {
	if _, ok := usc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserStats.user_id"`)}
	}
	if _, ok := usc.mutation.PostCount(); !ok {
		return &ValidationError{Name: "post_count", err: errors.New(`ent: missing required field "UserStats.post_count"`)}
	}
	if _, ok := usc.mutation.FollowerCount(); !ok {
		return &ValidationError{Name: "follower_count", err: errors.New(`ent: missing required field "UserStats.follower_count"`)}
	}
	if _, ok := usc.mutation.FollowingCount(); !ok {
		return &ValidationError{Name: "following_count", err: errors.New(`ent: missing required field "UserStats.following_count"`)}
	}
	if _, ok := usc.mutation.LikeReceivedCount(); !ok {
		return &ValidationError{Name: "like_received_count", err: errors.New(`ent: missing required field "UserStats.like_received_count"`)}
	}
	if _, ok := usc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserStats.created_at"`)}
	}
	if _, ok := usc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserStats.updated_at"`)}
	}
	return nil
}

func (usc *UserStatsCreate) sqlSave(ctx context.Context) (*UserStats, error) {
	if err := usc.check(); err != nil {
		return nil, err
	}
	_node, _spec := usc.createSpec()
	if err := sqlgraph.CreateNode(ctx, usc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	usc.mutation.id = &_node.ID
	usc.mutation.done = true
	return _node, nil
}

func (usc *UserStatsCreate) createSpec() (*UserStats, *sqlgraph.CreateSpec) {
	var (
		_node = &UserStats{config: usc.config}
		_spec = sqlgraph.NewCreateSpec(userstats.Table, sqlgraph.NewFieldSpec(userstats.FieldID, field.TypeUUID))
	)
	if id, ok := usc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := usc.mutation.UserID(); ok {
		_spec.SetField(userstats.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := usc.mutation.PostCount(); ok {
		_spec.SetField(userstats.FieldPostCount, field.TypeInt, value)
		_node.PostCount = value
	}
	if value, ok := usc.mutation.FollowerCount(); ok {
		_spec.SetField(userstats.FieldFollowerCount, field.TypeInt, value)
		_node.FollowerCount = value
	}
	if value, ok := usc.mutation.FollowingCount(); ok {
		_spec.SetField(userstats.FieldFollowingCount, field.TypeInt, value)
		_node.FollowingCount = value
	}
	if value, ok := usc.mutation.LikeReceivedCount(); ok {
		_spec.SetField(userstats.FieldLikeReceivedCount, field.TypeInt, value)
		_node.LikeReceivedCount = value
	}
	if value, ok := usc.mutation.CreatedAt(); ok {
		_spec.SetField(userstats.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := usc.mutation.UpdatedAt(); ok {
		_spec.SetField(userstats.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// UserStatsCreateBulk is the builder for creating many UserStats entities in bulk.
type UserStatsCreateBulk struct {
	config
	err      error
	builders []*UserStatsCreate
}

// Save creates the UserStats entities in the database.
func (uscb *UserStatsCreateBulk) Save(ctx context.Context) ([]*UserStats, error) {
	if uscb.err != nil {
		return nil, uscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(uscb.builders))
	nodes := make([]*UserStats, len(uscb.builders))
	mutators := make([]Mutator, len(uscb.builders))
	for i := range uscb.builders {
		func(i int, root context.Context) {
			builder := uscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserStatsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (uscb *UserStatsCreateBulk) SaveX(ctx context.Context) []*UserStats {
	v, err := uscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uscb *UserStatsCreateBulk) Exec(ctx context.Context) error {
	_, err := uscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uscb *UserStatsCreateBulk) ExecX(ctx context.Context) {
	if err := uscb.Exec(ctx); err != nil {
		panic(err)
	}
}
