// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"social-server/internal/ent/predicate"
	"social-server/internal/ent/usersession"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserSessionUpdate is the builder for updating UserSession entities.
type UserSessionUpdate struct {
	config
	hooks    []Hook
	mutation *UserSessionMutation
}

// Where appends a list predicates to the UserSessionUpdate builder.
func (usu *UserSessionUpdate) Where(ps ...predicate.UserSession) *UserSessionUpdate {
	usu.mutation.Where(ps...)
	return usu
}

// SetUserID sets the "user_id" field.
func (usu *UserSessionUpdate) SetUserID(u uuid.UUID) *UserSessionUpdate {
	usu.mutation.SetUserID(u)
	return usu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (usu *UserSessionUpdate) SetNillableUserID(u *uuid.UUID) *UserSessionUpdate {
	if u != nil {
		usu.SetUserID(*u)
	}
	return usu
}

// SetTokenID sets the "token_id" field.
func (usu *UserSessionUpdate) SetTokenID(s string) *UserSessionUpdate {
	usu.mutation.SetTokenID(s)
	return usu
}

// SetNillableTokenID sets the "token_id" field if the given value is not nil.
func (usu *UserSessionUpdate) SetNillableTokenID(s *string) *UserSessionUpdate {
	if s != nil {
		usu.SetTokenID(*s)
	}
	return usu
}

// SetDeviceInfo sets the "device_info" field.
func (usu *UserSessionUpdate) SetDeviceInfo(s string) *UserSessionUpdate {
	usu.mutation.SetDeviceInfo(s)
	return usu
}

// SetNillableDeviceInfo sets the "device_info" field if the given value is not nil.
func (usu *UserSessionUpdate) SetNillableDeviceInfo(s *string) *UserSessionUpdate {
	if s != nil {
		usu.SetDeviceInfo(*s)
	}
	return usu
}

// SetIPAddress sets the "ip_address" field.
func (usu *UserSessionUpdate) SetIPAddress(s string) *UserSessionUpdate {
	usu.mutation.SetIPAddress(s)
	return usu
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (usu *UserSessionUpdate) SetNillableIPAddress(s *string) *UserSessionUpdate {
	if s != nil {
		usu.SetIPAddress(*s)
	}
	return usu
}

// SetExpiresAt sets the "expires_at" field.
func (usu *UserSessionUpdate) SetExpiresAt(t time.Time) *UserSessionUpdate {
	usu.mutation.SetExpiresAt(t)
	return usu
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (usu *UserSessionUpdate) SetNillableExpiresAt(t *time.Time) *UserSessionUpdate {
	if t != nil {
		usu.SetExpiresAt(*t)
	}
	return usu
}

// Mutation returns the UserSessionMutation object of the builder.
func (usu *UserSessionUpdate) Mutation() *UserSessionMutation {
	return usu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (usu *UserSessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, usu.sqlSave, usu.mutation, usu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (usu *UserSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := usu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (usu *UserSessionUpdate) Exec(ctx context.Context) error {
	_, err := usu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (usu *UserSessionUpdate) ExecX(ctx context.Context) {
	if err := usu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (usu *UserSessionUpdate) check() error {
	if v, ok := usu.mutation.TokenID(); ok {
		if err := usersession.TokenIDValidator(v); err != nil {
			return &ValidationError{Name: "token_id", err: fmt.Errorf(`ent: validator failed for field "UserSession.token_id": %w`, err)}
		}
	}
	if v, ok := usu.mutation.DeviceInfo(); ok {
		if err := usersession.DeviceInfoValidator(v); err != nil {
			return &ValidationError{Name: "device_info", err: fmt.Errorf(`ent: validator failed for field "UserSession.device_info": %w`, err)}
		}
	}
	if v, ok := usu.mutation.IPAddress(); ok {
		if err := usersession.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "UserSession.ip_address": %w`, err)}
		}
	}
	return nil
}

func (usu *UserSessionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := usu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(usersession.Table, usersession.Columns, sqlgraph.NewFieldSpec(usersession.FieldID, field.TypeUUID))
	if ps := usu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := usu.mutation.UserID(); ok {
		_spec.SetField(usersession.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := usu.mutation.TokenID(); ok {
		_spec.SetField(usersession.FieldTokenID, field.TypeString, value)
	}
	if value, ok := usu.mutation.DeviceInfo(); ok {
		_spec.SetField(usersession.FieldDeviceInfo, field.TypeString, value)
	}
	if value, ok := usu.mutation.IPAddress(); ok {
		_spec.SetField(usersession.FieldIPAddress, field.TypeString, value)
	}
	if value, ok := usu.mutation.ExpiresAt(); ok {
		_spec.SetField(usersession.FieldExpiresAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, usu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	usu.mutation.done = true
	return n, nil
}

// UserSessionUpdateOne is the builder for updating a single UserSession entity.
type UserSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserSessionMutation
}

// SetUserID sets the "user_id" field.
func (usuo *UserSessionUpdateOne) SetUserID(u uuid.UUID) *UserSessionUpdateOne {
	usuo.mutation.SetUserID(u)
	return usuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (usuo *UserSessionUpdateOne) SetNillableUserID(u *uuid.UUID) *UserSessionUpdateOne {
	if u != nil {
		usuo.SetUserID(*u)
	}
	return usuo
}

// SetTokenID sets the "token_id" field.
func (usuo *UserSessionUpdateOne) SetTokenID(s string) *UserSessionUpdateOne {
	usuo.mutation.SetTokenID(s)
	return usuo
}

// SetNillableTokenID sets the "token_id" field if the given value is not nil.
func (usuo *UserSessionUpdateOne) SetNillableTokenID(s *string) *UserSessionUpdateOne {
	if s != nil {
		usuo.SetTokenID(*s)
	}
	return usuo
}

// SetDeviceInfo sets the "device_info" field.
func (usuo *UserSessionUpdateOne) SetDeviceInfo(s string) *UserSessionUpdateOne {
	usuo.mutation.SetDeviceInfo(s)
	return usuo
}

// SetNillableDeviceInfo sets the "device_info" field if the given value is not nil.
func (usuo *UserSessionUpdateOne) SetNillableDeviceInfo(s *string) *UserSessionUpdateOne {
	if s != nil {
		usuo.SetDeviceInfo(*s)
	}
	return usuo
}

// SetIPAddress sets the "ip_address" field.
func (usuo *UserSessionUpdateOne) SetIPAddress(s string) *UserSessionUpdateOne {
	usuo.mutation.SetIPAddress(s)
	return usuo
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (usuo *UserSessionUpdateOne) SetNillableIPAddress(s *string) *UserSessionUpdateOne {
	if s != nil {
		usuo.SetIPAddress(*s)
	}
	return usuo
}

// SetExpiresAt sets the "expires_at" field.
func (usuo *UserSessionUpdateOne) SetExpiresAt(t time.Time) *UserSessionUpdateOne {
	usuo.mutation.SetExpiresAt(t)
	return usuo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (usuo *UserSessionUpdateOne) SetNillableExpiresAt(t *time.Time) *UserSessionUpdateOne {
	if t != nil {
		usuo.SetExpiresAt(*t)
	}
	return usuo
}

// Mutation returns the UserSessionMutation object of the builder.
func (usuo *UserSessionUpdateOne) Mutation() *UserSessionMutation {
	return usuo.mutation
}

// Where appends a list predicates to the UserSessionUpdate builder.
func (usuo *UserSessionUpdateOne) Where(ps ...predicate.UserSession) *UserSessionUpdateOne {
	usuo.mutation.Where(ps...)
	return usuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (usuo *UserSessionUpdateOne) Select(field string, fields ...string) *UserSessionUpdateOne {
	usuo.fields = append([]string{field}, fields...)
	return usuo
}

// Save executes the query and returns the updated UserSession entity.
func (usuo *UserSessionUpdateOne) Save(ctx context.Context) (*UserSession, error) {
	return withHooks(ctx, usuo.sqlSave, usuo.mutation, usuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (usuo *UserSessionUpdateOne) SaveX(ctx context.Context) *UserSession {
	node, err := usuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (usuo *UserSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := usuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (usuo *UserSessionUpdateOne) ExecX(ctx context.Context) {
	if err := usuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (usuo *UserSessionUpdateOne) check() error {
	if v, ok := usuo.mutation.TokenID(); ok {
		if err := usersession.TokenIDValidator(v); err != nil {
			return &ValidationError{Name: "token_id", err: fmt.Errorf(`ent: validator failed for field "UserSession.token_id": %w`, err)}
		}
	}
	if v, ok := usuo.mutation.DeviceInfo(); ok {
		if err := usersession.DeviceInfoValidator(v); err != nil {
			return &ValidationError{Name: "device_info", err: fmt.Errorf(`ent: validator failed for field "UserSession.device_info": %w`, err)}
		}
	}
	if v, ok := usuo.mutation.IPAddress(); ok {
		if err := usersession.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "UserSession.ip_address": %w`, err)}
		}
	}
	return nil
}

func (usuo *UserSessionUpdateOne) sqlSave(ctx context.Context) (_node *UserSession, err error) {
	if err := usuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usersession.Table, usersession.Columns, sqlgraph.NewFieldSpec(usersession.FieldID, field.TypeUUID))
	id, ok := usuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := usuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usersession.FieldID)
		for _, f := range fields {
			if !usersession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usersession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := usuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := usuo.mutation.UserID(); ok {
		_spec.SetField(usersession.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := usuo.mutation.TokenID(); ok {
		_spec.SetField(usersession.FieldTokenID, field.TypeString, value)
	}
	if value, ok := usuo.mutation.DeviceInfo(); ok {
		_spec.SetField(usersession.FieldDeviceInfo, field.TypeString, value)
	}
	if value, ok := usuo.mutation.IPAddress(); ok {
		_spec.SetField(usersession.FieldIPAddress, field.TypeString, value)
	}
	if value, ok := usuo.mutation.ExpiresAt(); ok {
		_spec.SetField(usersession.FieldExpiresAt, field.TypeTime, value)
	}
	_node = &UserSession{config: usuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, usuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	usuo.mutation.done = true
	return _node, nil
}
