// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"social-server/internal/ent/userprofile"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserProfileCreate is the builder for creating a UserProfile entity.
type UserProfileCreate struct {
	config
	mutation *UserProfileMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (upc *UserProfileCreate) SetUserID(u uuid.UUID) *UserProfileCreate {
	upc.mutation.SetUserID(u)
	return upc
}

// SetDisplayName sets the "display_name" field.
func (upc *UserProfileCreate) SetDisplayName(s string) *UserProfileCreate {
	upc.mutation.SetDisplayName(s)
	return upc
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (upc *UserProfileCreate) SetNillableDisplayName(s *string) *UserProfileCreate {
	if s != nil {
		upc.SetDisplayName(*s)
	}
	return upc
}

// SetBio sets the "bio" field.
func (upc *UserProfileCreate) SetBio(s string) *UserProfileCreate {
	upc.mutation.SetBio(s)
	return upc
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (upc *UserProfileCreate) SetNillableBio(s *string) *UserProfileCreate {
	if s != nil {
		upc.SetBio(*s)
	}
	return upc
}

// SetAvatarURL sets the "avatar_url" field.
func (upc *UserProfileCreate) SetAvatarURL(s string) *UserProfileCreate {
	upc.mutation.SetAvatarURL(s)
	return upc
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (upc *UserProfileCreate) SetNillableAvatarURL(s *string) *UserProfileCreate {
	if s != nil {
		upc.SetAvatarURL(*s)
	}
	return upc
}

// SetCoverURL sets the "cover_url" field.
func (upc *UserProfileCreate) SetCoverURL(s string) *UserProfileCreate {
	upc.mutation.SetCoverURL(s)
	return upc
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (upc *UserProfileCreate) SetNillableCoverURL(s *string) *UserProfileCreate {
	if s != nil {
		upc.SetCoverURL(*s)
	}
	return upc
}

// SetLocation sets the "location" field.
func (upc *UserProfileCreate) SetLocation(s string) *UserProfileCreate {
	upc.mutation.SetLocation(s)
	return upc
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (upc *UserProfileCreate) SetNillableLocation(s *string) *UserProfileCreate {
	if s != nil {
		upc.SetLocation(*s)
	}
	return upc
}

// SetWebsite sets the "website" field.
func (upc *UserProfileCreate) SetWebsite(s string) *UserProfileCreate {
	upc.mutation.SetWebsite(s)
	return upc
}

// SetNillableWebsite sets the "website" field if the given value is not nil.
func (upc *UserProfileCreate) SetNillableWebsite(s *string) *UserProfileCreate {
	if s != nil {
		upc.SetWebsite(*s)
	}
	return upc
}

// SetCreatedAt sets the "created_at" field.
func (upc *UserProfileCreate) SetCreatedAt(t time.Time) *UserProfileCreate {
	upc.mutation.SetCreatedAt(t)
	return upc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (upc *UserProfileCreate) SetNillableCreatedAt(t *time.Time) *UserProfileCreate {
	if t != nil {
		upc.SetCreatedAt(*t)
	}
	return upc
}

// SetUpdatedAt sets the "updated_at" field.
func (upc *UserProfileCreate) SetUpdatedAt(t time.Time) *UserProfileCreate {
	upc.mutation.SetUpdatedAt(t)
	return upc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (upc *UserProfileCreate) SetNillableUpdatedAt(t *time.Time) *UserProfileCreate {
	if t != nil {
		upc.SetUpdatedAt(*t)
	}
	return upc
}

// SetID sets the "id" field.
func (upc *UserProfileCreate) SetID(u uuid.UUID) *UserProfileCreate {
	upc.mutation.SetID(u)
	return upc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (upc *UserProfileCreate) SetNillableID(u *uuid.UUID) *UserProfileCreate {
	if u != nil {
		upc.SetID(*u)
	}
	return upc
}

// Mutation returns the UserProfileMutation object of the builder.
func (upc *UserProfileCreate) Mutation() *UserProfileMutation {
	return upc.mutation
}

// Save creates the UserProfile in the database.
func (upc *UserProfileCreate) Save(ctx context.Context) (*UserProfile, error) {
	upc.defaults()
	return withHooks(ctx, upc.sqlSave, upc.mutation, upc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (upc *UserProfileCreate) SaveX(ctx context.Context) *UserProfile {
	v, err := upc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (upc *UserProfileCreate) Exec(ctx context.Context) error {
	_, err := upc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (upc *UserProfileCreate) ExecX(ctx context.Context) {
	if err := upc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (upc *UserProfileCreate) defaults() {
	if _, ok := upc.mutation.DisplayName(); !ok {
		v := userprofile.DefaultDisplayName
		upc.mutation.SetDisplayName(v)
	}
	if _, ok := upc.mutation.Bio(); !ok {
		v := userprofile.DefaultBio
		upc.mutation.SetBio(v)
	}
	if _, ok := upc.mutation.AvatarURL(); !ok {
		v := userprofile.DefaultAvatarURL
		upc.mutation.SetAvatarURL(v)
	}
	if _, ok := upc.mutation.CoverURL(); !ok {
		v := userprofile.DefaultCoverURL
		upc.mutation.SetCoverURL(v)
	}
	if _, ok := upc.mutation.Location(); !ok {
		v := userprofile.DefaultLocation
		upc.mutation.SetLocation(v)
	}
	if _, ok := upc.mutation.Website(); !ok {
		v := userprofile.DefaultWebsite
		upc.mutation.SetWebsite(v)
	}
	if _, ok := upc.mutation.CreatedAt(); !ok {
		v := userprofile.DefaultCreatedAt()
		upc.mutation.SetCreatedAt(v)
	}
	if _, ok := upc.mutation.UpdatedAt(); !ok {
		v := userprofile.DefaultUpdatedAt()
		upc.mutation.SetUpdatedAt(v)
	}
	if _, ok := upc.mutation.ID(); !ok {
		v := userprofile.DefaultID()
		upc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (upc *UserProfileCreate) check() error {
	if _, ok := upc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserProfile.user_id"`)}
	}
	if _, ok := upc.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "UserProfile.display_name"`)}
	}
	if v, ok := upc.mutation.DisplayName(); ok {
		if err := userprofile.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "UserProfile.display_name": %w`, err)}
		}
	}
	if _, ok := upc.mutation.Bio(); !ok {
		return &ValidationError{Name: "bio", err: errors.New(`ent: missing required field "UserProfile.bio"`)}
	}
	if v, ok := upc.mutation.Bio(); ok {
		if err := userprofile.BioValidator(v); err != nil {
			return &ValidationError{Name: "bio", err: fmt.Errorf(`ent: validator failed for field "UserProfile.bio": %w`, err)}
		}
	}
	if _, ok := upc.mutation.AvatarURL(); !ok {
		return &ValidationError{Name: "avatar_url", err: errors.New(`ent: missing required field "UserProfile.avatar_url"`)}
	}
	if v, ok := upc.mutation.AvatarURL(); ok {
		if err := userprofile.AvatarURLValidator(v); err != nil {
			return &ValidationError{Name: "avatar_url", err: fmt.Errorf(`ent: validator failed for field "UserProfile.avatar_url": %w`, err)}
		}
	}
	if _, ok := upc.mutation.CoverURL(); !ok {
		return &ValidationError{Name: "cover_url", err: errors.New(`ent: missing required field "UserProfile.cover_url"`)}
	}
	if v, ok := upc.mutation.CoverURL(); ok {
		if err := userprofile.CoverURLValidator(v); err != nil {
			return &ValidationError{Name: "cover_url", err: fmt.Errorf(`ent: validator failed for field "UserProfile.cover_url": %w`, err)}
		}
	}
	if _, ok := upc.mutation.Location(); !ok {
		return &ValidationError{Name: "location", err: errors.New(`ent: missing required field "UserProfile.location"`)}
	}
	if v, ok := upc.mutation.Location(); ok {
		if err := userprofile.LocationValidator(v); err != nil {
			return &ValidationError{Name: "location", err: fmt.Errorf(`ent: validator failed for field "UserProfile.location": %w`, err)}
		}
	}
	if _, ok := upc.mutation.Website(); !ok {
		return &ValidationError{Name: "website", err: errors.New(`ent: missing required field "UserProfile.website"`)}
	}
	if v, ok := upc.mutation.Website(); ok {
		if err := userprofile.WebsiteValidator(v); err != nil {
			return &ValidationError{Name: "website", err: fmt.Errorf(`ent: validator failed for field "UserProfile.website": %w`, err)}
		}
	}
	if _, ok := upc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserProfile.created_at"`)}
	}
	if _, ok := upc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserProfile.updated_at"`)}
	}
	return nil
}

func (upc *UserProfileCreate) sqlSave(ctx context.Context) (*UserProfile, error) {
	if err := upc.check(); err != nil {
		return nil, err
	}
	_node, _spec := upc.createSpec()
	if err := sqlgraph.CreateNode(ctx, upc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	upc.mutation.id = &_node.ID
	upc.mutation.done = true
	return _node, nil
}

func (upc *UserProfileCreate) createSpec() (*UserProfile, *sqlgraph.CreateSpec) {
	var (
		_node = &UserProfile{config: upc.config}
		_spec = sqlgraph.NewCreateSpec(userprofile.Table, sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeUUID))
	)
	if id, ok := upc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := upc.mutation.UserID(); ok {
		_spec.SetField(userprofile.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := upc.mutation.DisplayName(); ok {
		_spec.SetField(userprofile.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := upc.mutation.Bio(); ok {
		_spec.SetField(userprofile.FieldBio, field.TypeString, value)
		_node.Bio = value
	}
	if value, ok := upc.mutation.AvatarURL(); ok {
		_spec.SetField(userprofile.FieldAvatarURL, field.TypeString, value)
		_node.AvatarURL = value
	}
	if value, ok := upc.mutation.CoverURL(); ok {
		_spec.SetField(userprofile.FieldCoverURL, field.TypeString, value)
		_node.CoverURL = value
	}
	if value, ok := upc.mutation.Location(); ok {
		_spec.SetField(userprofile.FieldLocation, field.TypeString, value)
		_node.Location = value
	}
	if value, ok := upc.mutation.Website(); ok {
		_spec.SetField(userprofile.FieldWebsite, field.TypeString, value)
		_node.Website = value
	}
	if value, ok := upc.mutation.CreatedAt(); ok {
		_spec.SetField(userprofile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := upc.mutation.UpdatedAt(); ok {
		_spec.SetField(userprofile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// UserProfileCreateBulk is the builder for creating many UserProfile entities in bulk.
type UserProfileCreateBulk struct {
	config
	err      error
	builders []*UserProfileCreate
}

// Save creates the UserProfile entities in the database.
func (upcb *UserProfileCreateBulk) Save(ctx context.Context) ([]*UserProfile, error) {
	if upcb.err != nil {
		return nil, upcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(upcb.builders))
	nodes := make([]*UserProfile, len(upcb.builders))
	mutators := make([]Mutator, len(upcb.builders))
	for i := range upcb.builders {
		func(i int, root context.Context) {
			builder := upcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserProfileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, upcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, upcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, upcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (upcb *UserProfileCreateBulk) SaveX(ctx context.Context) []*UserProfile {
	v, err := upcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (upcb *UserProfileCreateBulk) Exec(ctx context.Context) error {
	_, err := upcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (upcb *UserProfileCreateBulk) ExecX(ctx context.Context) {
	if err := upcb.Exec(ctx); err != nil {
		panic(err)
	}
}
