// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"social-server/internal/ent/userstats"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserStatsCreate is the builder for creating a UserStats entity.
type UserStatsCreate struct {
	config
	mutation *UserStatsMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *UserStatsCreate) SetUserID(v uuid.UUID) *UserStatsCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPostCount sets the "post_count" field.
func (_c *UserStatsCreate) SetPostCount(v int) *UserStatsCreate {
	_c.mutation.SetPostCount(v)
	return _c
}

// SetNillablePostCount sets the "post_count" field if the given value is not nil.
func (_c *UserStatsCreate) SetNillablePostCount(v *int) *UserStatsCreate {
	if v != nil {
		_c.SetPostCount(*v)
	}
	return _c
}

// SetFollowerCount sets the "follower_count" field.
func (_c *UserStatsCreate) SetFollowerCount(v int) *UserStatsCreate {
	_c.mutation.SetFollowerCount(v)
	return _c
}

// SetNillableFollowerCount sets the "follower_count" field if the given value is not nil.
func (_c *UserStatsCreate) SetNillableFollowerCount(v *int) *UserStatsCreate {
	if v != nil {
		_c.SetFollowerCount(*v)
	}
	return _c
}

// SetFollowingCount sets the "following_count" field.
func (_c *UserStatsCreate) SetFollowingCount(v int) *UserStatsCreate {
	_c.mutation.SetFollowingCount(v)
	return _c
}

// SetNillableFollowingCount sets the "following_count" field if the given value is not nil.
func (_c *UserStatsCreate) SetNillableFollowingCount(v *int) *UserStatsCreate {
	if v != nil {
		_c.SetFollowingCount(*v)
	}
	return _c
}

// SetLikeReceivedCount sets the "like_received_count" field.
func (_c *UserStatsCreate) SetLikeReceivedCount(v int) *UserStatsCreate {
	_c.mutation.SetLikeReceivedCount(v)
	return _c
}

// SetNillableLikeReceivedCount sets the "like_received_count" field if the given value is not nil.
func (_c *UserStatsCreate) SetNillableLikeReceivedCount(v *int) *UserStatsCreate {
	if v != nil {
		_c.SetLikeReceivedCount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserStatsCreate) SetCreatedAt(v time.Time) *UserStatsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserStatsCreate) SetNillableCreatedAt(v *time.Time) *UserStatsCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserStatsCreate) SetUpdatedAt(v time.Time) *UserStatsCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserStatsCreate) SetNillableUpdatedAt(v *time.Time) *UserStatsCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserStatsCreate) SetID(v uuid.UUID) *UserStatsCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UserStatsCreate) SetNillableID(v *uuid.UUID) *UserStatsCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the UserStatsMutation object of the builder.
func (_c *UserStatsCreate) Mutation() *UserStatsMutation {
	return _c.mutation
}

// Save creates the UserStats in the database.
func (_c *UserStatsCreate) Save(ctx context.Context) (*UserStats, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserStatsCreate) SaveX(ctx context.Context) *UserStats {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserStatsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserStatsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserStatsCreate) defaults() {
	if _, ok := _c.mutation.PostCount(); !ok {
		v := userstats.DefaultPostCount
		_c.mutation.SetPostCount(v)
	}
	if _, ok := _c.mutation.FollowerCount(); !ok {
		v := userstats.DefaultFollowerCount
		_c.mutation.SetFollowerCount(v)
	}
	if _, ok := _c.mutation.FollowingCount(); !ok {
		v := userstats.DefaultFollowingCount
		_c.mutation.SetFollowingCount(v)
	}
	if _, ok := _c.mutation.LikeReceivedCount(); !ok {
		v := userstats.DefaultLikeReceivedCount
		_c.mutation.SetLikeReceivedCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userstats.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userstats.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := userstats.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserStatsCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserStats.user_id"`)}
	}
	if _, ok := _c.mutation.PostCount(); !ok {
		return &ValidationError{Name: "post_count", err: errors.New(`ent: missing required field "UserStats.post_count"`)}
	}
	if _, ok := _c.mutation.FollowerCount(); !ok {
		return &ValidationError{Name: "follower_count", err: errors.New(`ent: missing required field "UserStats.follower_count"`)}
	}
	if _, ok := _c.mutation.FollowingCount(); !ok {
		return &ValidationError{Name: "following_count", err: errors.New(`ent: missing required field "UserStats.following_count"`)}
	}
	if _, ok := _c.mutation.LikeReceivedCount(); !ok {
		return &ValidationError{Name: "like_received_count", err: errors.New(`ent: missing required field "UserStats.like_received_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserStats.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserStats.updated_at"`)}
	}
	return nil
}

func (_c *UserStatsCreate) sqlSave(ctx context.Context) (*UserStats, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserStatsCreate) createSpec() (*UserStats, *sqlgraph.CreateSpec) {
	var (
		_node = &UserStats{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userstats.Table, sqlgraph.NewFieldSpec(userstats.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(userstats.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.PostCount(); ok {
		_spec.SetField(userstats.FieldPostCount, field.TypeInt, value)
		_node.PostCount = value
	}
	if value, ok := _c.mutation.FollowerCount(); ok {
		_spec.SetField(userstats.FieldFollowerCount, field.TypeInt, value)
		_node.FollowerCount = value
	}
	if value, ok := _c.mutation.FollowingCount(); ok {
		_spec.SetField(userstats.FieldFollowingCount, field.TypeInt, value)
		_node.FollowingCount = value
	}
	if value, ok := _c.mutation.LikeReceivedCount(); ok {
		_spec.SetField(userstats.FieldLikeReceivedCount, field.TypeInt, value)
		_node.LikeReceivedCount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userstats.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userstats.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// UserStatsCreateBulk is the builder for creating many UserStats entities in bulk.
type UserStatsCreateBulk struct {
	config
	err      error
	builders []*UserStatsCreate
}

// Save creates the UserStats entities in the database.
func (_c *UserStatsCreateBulk) Save(ctx context.Context) ([]*UserStats, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserStats, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserStatsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserStatsCreateBulk) SaveX(ctx context.Context) []*UserStats {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserStatsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserStatsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
