// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"social-server/internal/ent/predicate"
	"social-server/internal/ent/userprofile"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserProfileUpdate is the builder for updating UserProfile entities.
type UserProfileUpdate struct {
	config
	hooks    []Hook
	mutation *UserProfileMutation
}

// Where appends a list predicates to the UserProfileUpdate builder.
func (_u *UserProfileUpdate) Where(ps ...predicate.UserProfile) *UserProfileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserProfileUpdate) SetUserID(v uuid.UUID) *UserProfileUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserProfileUpdate) SetNillableUserID(v *uuid.UUID) *UserProfileUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *UserProfileUpdate) SetDisplayName(v string) *UserProfileUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *UserProfileUpdate) SetNillableDisplayName(v *string) *UserProfileUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetBio sets the "bio" field.
func (_u *UserProfileUpdate) SetBio(v string) *UserProfileUpdate {
	_u.mutation.SetBio(v)
	return _u
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (_u *UserProfileUpdate) SetNillableBio(v *string) *UserProfileUpdate {
	if v != nil {
		_u.SetBio(*v)
	}
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *UserProfileUpdate) SetAvatarURL(v string) *UserProfileUpdate {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *UserProfileUpdate) SetNillableAvatarURL(v *string) *UserProfileUpdate {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// SetCoverURL sets the "cover_url" field.
func (_u *UserProfileUpdate) SetCoverURL(v string) *UserProfileUpdate {
	_u.mutation.SetCoverURL(v)
	return _u
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_u *UserProfileUpdate) SetNillableCoverURL(v *string) *UserProfileUpdate {
	if v != nil {
		_u.SetCoverURL(*v)
	}
	return _u
}

// SetLocation sets the "location" field.
func (_u *UserProfileUpdate) SetLocation(v string) *UserProfileUpdate {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *UserProfileUpdate) SetNillableLocation(v *string) *UserProfileUpdate {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// SetWebsite sets the "website" field.
func (_u *UserProfileUpdate) SetWebsite(v string) *UserProfileUpdate {
	_u.mutation.SetWebsite(v)
	return _u
}

// SetNillableWebsite sets the "website" field if the given value is not nil.
func (_u *UserProfileUpdate) SetNillableWebsite(v *string) *UserProfileUpdate {
	if v != nil {
		_u.SetWebsite(*v)
	}
	return _u
}

// Mutation returns the UserProfileMutation object of the builder.
func (_u *UserProfileUpdate) Mutation() *UserProfileMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserProfileUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserProfileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserProfileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserProfileUpdate) check() error {
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := userprofile.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "UserProfile.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Bio(); ok {
		if err := userprofile.BioValidator(v); err != nil {
			return &ValidationError{Name: "bio", err: fmt.Errorf(`ent: validator failed for field "UserProfile.bio": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AvatarURL(); ok {
		if err := userprofile.AvatarURLValidator(v); err != nil {
			return &ValidationError{Name: "avatar_url", err: fmt.Errorf(`ent: validator failed for field "UserProfile.avatar_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverURL(); ok {
		if err := userprofile.CoverURLValidator(v); err != nil {
			return &ValidationError{Name: "cover_url", err: fmt.Errorf(`ent: validator failed for field "UserProfile.cover_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Location(); ok {
		if err := userprofile.LocationValidator(v); err != nil {
			return &ValidationError{Name: "location", err: fmt.Errorf(`ent: validator failed for field "UserProfile.location": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Website(); ok {
		if err := userprofile.WebsiteValidator(v); err != nil {
			return &ValidationError{Name: "website", err: fmt.Errorf(`ent: validator failed for field "UserProfile.website": %w`, err)}
		}
	}
	return nil
}

func (_u *UserProfileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userprofile.Table, userprofile.Columns, sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(userprofile.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(userprofile.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bio(); ok {
		_spec.SetField(userprofile.FieldBio, field.TypeString, value)
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(userprofile.FieldAvatarURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.CoverURL(); ok {
		_spec.SetField(userprofile.FieldCoverURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(userprofile.FieldLocation, field.TypeString, value)
	}
	if value, ok := _u.mutation.Website(); ok {
		_spec.SetField(userprofile.FieldWebsite, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserProfileUpdateOne is the builder for updating a single UserProfile entity.
type UserProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserProfileMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserProfileUpdateOne) SetUserID(v uuid.UUID) *UserProfileUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserProfileUpdateOne) SetNillableUserID(v *uuid.UUID) *UserProfileUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *UserProfileUpdateOne) SetDisplayName(v string) *UserProfileUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *UserProfileUpdateOne) SetNillableDisplayName(v *string) *UserProfileUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetBio sets the "bio" field.
func (_u *UserProfileUpdateOne) SetBio(v string) *UserProfileUpdateOne {
	_u.mutation.SetBio(v)
	return _u
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (_u *UserProfileUpdateOne) SetNillableBio(v *string) *UserProfileUpdateOne {
	if v != nil {
		_u.SetBio(*v)
	}
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *UserProfileUpdateOne) SetAvatarURL(v string) *UserProfileUpdateOne {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *UserProfileUpdateOne) SetNillableAvatarURL(v *string) *UserProfileUpdateOne {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// SetCoverURL sets the "cover_url" field.
func (_u *UserProfileUpdateOne) SetCoverURL(v string) *UserProfileUpdateOne {
	_u.mutation.SetCoverURL(v)
	return _u
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_u *UserProfileUpdateOne) SetNillableCoverURL(v *string) *UserProfileUpdateOne {
	if v != nil {
		_u.SetCoverURL(*v)
	}
	return _u
}

// SetLocation sets the "location" field.
func (_u *UserProfileUpdateOne) SetLocation(v string) *UserProfileUpdateOne {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *UserProfileUpdateOne) SetNillableLocation(v *string) *UserProfileUpdateOne {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// SetWebsite sets the "website" field.
func (_u *UserProfileUpdateOne) SetWebsite(v string) *UserProfileUpdateOne {
	_u.mutation.SetWebsite(v)
	return _u
}

// SetNillableWebsite sets the "website" field if the given value is not nil.
func (_u *UserProfileUpdateOne) SetNillableWebsite(v *string) *UserProfileUpdateOne {
	if v != nil {
		_u.SetWebsite(*v)
	}
	return _u
}

// Mutation returns the UserProfileMutation object of the builder.
func (_u *UserProfileUpdateOne) Mutation() *UserProfileMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserProfileUpdate builder.
func (_u *UserProfileUpdateOne) Where(ps ...predicate.UserProfile) *UserProfileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserProfileUpdateOne) Select(field string, fields ...string) *UserProfileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserProfile entity.
func (_u *UserProfileUpdateOne) Save(ctx context.Context) (*UserProfile, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserProfileUpdateOne) SaveX(ctx context.Context) *UserProfile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserProfileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserProfileUpdateOne) check() error {
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := userprofile.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "UserProfile.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Bio(); ok {
		if err := userprofile.BioValidator(v); err != nil {
			return &ValidationError{Name: "bio", err: fmt.Errorf(`ent: validator failed for field "UserProfile.bio": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AvatarURL(); ok {
		if err := userprofile.AvatarURLValidator(v); err != nil {
			return &ValidationError{Name: "avatar_url", err: fmt.Errorf(`ent: validator failed for field "UserProfile.avatar_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverURL(); ok {
		if err := userprofile.CoverURLValidator(v); err != nil {
			return &ValidationError{Name: "cover_url", err: fmt.Errorf(`ent: validator failed for field "UserProfile.cover_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Location(); ok {
		if err := userprofile.LocationValidator(v); err != nil {
			return &ValidationError{Name: "location", err: fmt.Errorf(`ent: validator failed for field "UserProfile.location": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Website(); ok {
		if err := userprofile.WebsiteValidator(v); err != nil {
			return &ValidationError{Name: "website", err: fmt.Errorf(`ent: validator failed for field "UserProfile.website": %w`, err)}
		}
	}
	return nil
}

func (_u *UserProfileUpdateOne) sqlSave(ctx context.Context) (_node *UserProfile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userprofile.Table, userprofile.Columns, sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userprofile.FieldID)
		for _, f := range fields {
			if !userprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(userprofile.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(userprofile.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bio(); ok {
		_spec.SetField(userprofile.FieldBio, field.TypeString, value)
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(userprofile.FieldAvatarURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.CoverURL(); ok {
		_spec.SetField(userprofile.FieldCoverURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(userprofile.FieldLocation, field.TypeString, value)
	}
	if value, ok := _u.mutation.Website(); ok {
		_spec.SetField(userprofile.FieldWebsite, field.TypeString, value)
	}
	_node = &UserProfile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
