// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"social-server/internal/ent/predicate"
	"social-server/internal/ent/userstats"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserStatsUpdate is the builder for updating UserStats entities.
type UserStatsUpdate struct {
	config
	hooks    []Hook
	mutation *UserStatsMutation
}

// Where appends a list predicates to the UserStatsUpdate builder.
func (_u *UserStatsUpdate) Where(ps ...predicate.UserStats) *UserStatsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserStatsUpdate) SetUserID(v uuid.UUID) *UserStatsUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserStatsUpdate) SetNillableUserID(v *uuid.UUID) *UserStatsUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPostCount sets the "post_count" field.
func (_u *UserStatsUpdate) SetPostCount(v int) *UserStatsUpdate {
	_u.mutation.ResetPostCount()
	_u.mutation.SetPostCount(v)
	return _u
}

// SetNillablePostCount sets the "post_count" field if the given value is not nil.
func (_u *UserStatsUpdate) SetNillablePostCount(v *int) *UserStatsUpdate {
	if v != nil {
		_u.SetPostCount(*v)
	}
	return _u
}

// AddPostCount adds value to the "post_count" field.
func (_u *UserStatsUpdate) AddPostCount(v int) *UserStatsUpdate {
	_u.mutation.AddPostCount(v)
	return _u
}

// SetFollowerCount sets the "follower_count" field.
func (_u *UserStatsUpdate) SetFollowerCount(v int) *UserStatsUpdate {
	_u.mutation.ResetFollowerCount()
	_u.mutation.SetFollowerCount(v)
	return _u
}

// SetNillableFollowerCount sets the "follower_count" field if the given value is not nil.
func (_u *UserStatsUpdate) SetNillableFollowerCount(v *int) *UserStatsUpdate {
	if v != nil {
		_u.SetFollowerCount(*v)
	}
	return _u
}

// AddFollowerCount adds value to the "follower_count" field.
func (_u *UserStatsUpdate) AddFollowerCount(v int) *UserStatsUpdate {
	_u.mutation.AddFollowerCount(v)
	return _u
}

// SetFollowingCount sets the "following_count" field.
func (_u *UserStatsUpdate) SetFollowingCount(v int) *UserStatsUpdate {
	_u.mutation.ResetFollowingCount()
	_u.mutation.SetFollowingCount(v)
	return _u
}

// SetNillableFollowingCount sets the "following_count" field if the given value is not nil.
func (_u *UserStatsUpdate) SetNillableFollowingCount(v *int) *UserStatsUpdate {
	if v != nil {
		_u.SetFollowingCount(*v)
	}
	return _u
}

// AddFollowingCount adds value to the "following_count" field.
func (_u *UserStatsUpdate) AddFollowingCount(v int) *UserStatsUpdate {
	_u.mutation.AddFollowingCount(v)
	return _u
}

// SetLikeReceivedCount sets the "like_received_count" field.
func (_u *UserStatsUpdate) SetLikeReceivedCount(v int) *UserStatsUpdate {
	_u.mutation.ResetLikeReceivedCount()
	_u.mutation.SetLikeReceivedCount(v)
	return _u
}

// SetNillableLikeReceivedCount sets the "like_received_count" field if the given value is not nil.
func (_u *UserStatsUpdate) SetNillableLikeReceivedCount(v *int) *UserStatsUpdate {
	if v != nil {
		_u.SetLikeReceivedCount(*v)
	}
	return _u
}

// AddLikeReceivedCount adds value to the "like_received_count" field.
func (_u *UserStatsUpdate) AddLikeReceivedCount(v int) *UserStatsUpdate {
	_u.mutation.AddLikeReceivedCount(v)
	return _u
}

// Mutation returns the UserStatsMutation object of the builder.
func (_u *UserStatsUpdate) Mutation() *UserStatsMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserStatsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserStatsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserStatsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserStatsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UserStatsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(userstats.Table, userstats.Columns, sqlgraph.NewFieldSpec(userstats.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(userstats.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.PostCount(); ok {
		_spec.SetField(userstats.FieldPostCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPostCount(); ok {
		_spec.AddField(userstats.FieldPostCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FollowerCount(); ok {
		_spec.SetField(userstats.FieldFollowerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFollowerCount(); ok {
		_spec.AddField(userstats.FieldFollowerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FollowingCount(); ok {
		_spec.SetField(userstats.FieldFollowingCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFollowingCount(); ok {
		_spec.AddField(userstats.FieldFollowingCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LikeReceivedCount(); ok {
		_spec.SetField(userstats.FieldLikeReceivedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLikeReceivedCount(); ok {
		_spec.AddField(userstats.FieldLikeReceivedCount, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userstats.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserStatsUpdateOne is the builder for updating a single UserStats entity.
type UserStatsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserStatsMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserStatsUpdateOne) SetUserID(v uuid.UUID) *UserStatsUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserStatsUpdateOne) SetNillableUserID(v *uuid.UUID) *UserStatsUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPostCount sets the "post_count" field.
func (_u *UserStatsUpdateOne) SetPostCount(v int) *UserStatsUpdateOne {
	_u.mutation.ResetPostCount()
	_u.mutation.SetPostCount(v)
	return _u
}

// SetNillablePostCount sets the "post_count" field if the given value is not nil.
func (_u *UserStatsUpdateOne) SetNillablePostCount(v *int) *UserStatsUpdateOne {
	if v != nil {
		_u.SetPostCount(*v)
	}
	return _u
}

// AddPostCount adds value to the "post_count" field.
func (_u *UserStatsUpdateOne) AddPostCount(v int) *UserStatsUpdateOne {
	_u.mutation.AddPostCount(v)
	return _u
}

// SetFollowerCount sets the "follower_count" field.
func (_u *UserStatsUpdateOne) SetFollowerCount(v int) *UserStatsUpdateOne {
	_u.mutation.ResetFollowerCount()
	_u.mutation.SetFollowerCount(v)
	return _u
}

// SetNillableFollowerCount sets the "follower_count" field if the given value is not nil.
func (_u *UserStatsUpdateOne) SetNillableFollowerCount(v *int) *UserStatsUpdateOne {
	if v != nil {
		_u.SetFollowerCount(*v)
	}
	return _u
}

// AddFollowerCount adds value to the "follower_count" field.
func (_u *UserStatsUpdateOne) AddFollowerCount(v int) *UserStatsUpdateOne {
	_u.mutation.AddFollowerCount(v)
	return _u
}

// SetFollowingCount sets the "following_count" field.
func (_u *UserStatsUpdateOne) SetFollowingCount(v int) *UserStatsUpdateOne {
	_u.mutation.ResetFollowingCount()
	_u.mutation.SetFollowingCount(v)
	return _u
}

// SetNillableFollowingCount sets the "following_count" field if the given value is not nil.
func (_u *UserStatsUpdateOne) SetNillableFollowingCount(v *int) *UserStatsUpdateOne {
	if v != nil {
		_u.SetFollowingCount(*v)
	}
	return _u
}

// AddFollowingCount adds value to the "following_count" field.
func (_u *UserStatsUpdateOne) AddFollowingCount(v int) *UserStatsUpdateOne {
	_u.mutation.AddFollowingCount(v)
	return _u
}

// SetLikeReceivedCount sets the "like_received_count" field.
func (_u *UserStatsUpdateOne) SetLikeReceivedCount(v int) *UserStatsUpdateOne {
	_u.mutation.ResetLikeReceivedCount()
	_u.mutation.SetLikeReceivedCount(v)
	return _u
}

// SetNillableLikeReceivedCount sets the "like_received_count" field if the given value is not nil.
func (_u *UserStatsUpdateOne) SetNillableLikeReceivedCount(v *int) *UserStatsUpdateOne {
	if v != nil {
		_u.SetLikeReceivedCount(*v)
	}
	return _u
}

// AddLikeReceivedCount adds value to the "like_received_count" field.
func (_u *UserStatsUpdateOne) AddLikeReceivedCount(v int) *UserStatsUpdateOne {
	_u.mutation.AddLikeReceivedCount(v)
	return _u
}

// Mutation returns the UserStatsMutation object of the builder.
func (_u *UserStatsUpdateOne) Mutation() *UserStatsMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserStatsUpdate builder.
func (_u *UserStatsUpdateOne) Where(ps ...predicate.UserStats) *UserStatsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserStatsUpdateOne) Select(field string, fields ...string) *UserStatsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserStats entity.
func (_u *UserStatsUpdateOne) Save(ctx context.Context) (*UserStats, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserStatsUpdateOne) SaveX(ctx context.Context) *UserStats {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserStatsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserStatsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UserStatsUpdateOne) sqlSave(ctx context.Context) (_node *UserStats, err error) {
	_spec := sqlgraph.NewUpdateSpec(userstats.Table, userstats.Columns, sqlgraph.NewFieldSpec(userstats.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserStats.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userstats.FieldID)
		for _, f := range fields {
			if !userstats.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userstats.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(userstats.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.PostCount(); ok {
		_spec.SetField(userstats.FieldPostCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPostCount(); ok {
		_spec.AddField(userstats.FieldPostCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FollowerCount(); ok {
		_spec.SetField(userstats.FieldFollowerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFollowerCount(); ok {
		_spec.AddField(userstats.FieldFollowerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FollowingCount(); ok {
		_spec.SetField(userstats.FieldFollowingCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFollowingCount(); ok {
		_spec.AddField(userstats.FieldFollowingCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LikeReceivedCount(); ok {
		_spec.SetField(userstats.FieldLikeReceivedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLikeReceivedCount(); ok {
		_spec.AddField(userstats.FieldLikeReceivedCount, field.TypeInt, value)
	}
	_node = &UserStats{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userstats.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
