// Code generated by ent, DO NOT EDIT.

package report

import (
	"social-server/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldID, id))
}

// ReporterID applies equality check predicate on the "reporter_id" field. It's identical to ReporterIDEQ.
func ReporterID(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldReporterID, v))
}

// TargetUserID applies equality check predicate on the "target_user_id" field. It's identical to TargetUserIDEQ.
func TargetUserID(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldTargetUserID, v))
}

// TargetPostID applies equality check predicate on the "target_post_id" field. It's identical to TargetPostIDEQ.
func TargetPostID(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldTargetPostID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldType, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldReason, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldStatus, v))
}

// ReviewNotes applies equality check predicate on the "review_notes" field. It's identical to ReviewNotesEQ.
func ReviewNotes(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldReviewNotes, v))
}

// ReviewedBy applies equality check predicate on the "reviewed_by" field. It's identical to ReviewedByEQ.
func ReviewedBy(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldReviewedBy, v))
}

// ReviewedAt applies equality check predicate on the "reviewed_at" field. It's identical to ReviewedAtEQ.
func ReviewedAt(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldReviewedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldCreatedAt, v))
}

// ReporterIDEQ applies the EQ predicate on the "reporter_id" field.
func ReporterIDEQ(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldReporterID, v))
}

// ReporterIDNEQ applies the NEQ predicate on the "reporter_id" field.
func ReporterIDNEQ(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldReporterID, v))
}

// ReporterIDIn applies the In predicate on the "reporter_id" field.
func ReporterIDIn(vs ...uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldReporterID, vs...))
}

// ReporterIDNotIn applies the NotIn predicate on the "reporter_id" field.
func ReporterIDNotIn(vs ...uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldReporterID, vs...))
}

// ReporterIDGT applies the GT predicate on the "reporter_id" field.
func ReporterIDGT(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldReporterID, v))
}

// ReporterIDGTE applies the GTE predicate on the "reporter_id" field.
func ReporterIDGTE(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldReporterID, v))
}

// ReporterIDLT applies the LT predicate on the "reporter_id" field.
func ReporterIDLT(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldReporterID, v))
}

// ReporterIDLTE applies the LTE predicate on the "reporter_id" field.
func ReporterIDLTE(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldReporterID, v))
}

// TargetUserIDEQ applies the EQ predicate on the "target_user_id" field.
func TargetUserIDEQ(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldTargetUserID, v))
}

// TargetUserIDNEQ applies the NEQ predicate on the "target_user_id" field.
func TargetUserIDNEQ(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldTargetUserID, v))
}

// TargetUserIDIn applies the In predicate on the "target_user_id" field.
func TargetUserIDIn(vs ...uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldTargetUserID, vs...))
}

// TargetUserIDNotIn applies the NotIn predicate on the "target_user_id" field.
func TargetUserIDNotIn(vs ...uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldTargetUserID, vs...))
}

// TargetUserIDGT applies the GT predicate on the "target_user_id" field.
func TargetUserIDGT(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldTargetUserID, v))
}

// TargetUserIDGTE applies the GTE predicate on the "target_user_id" field.
func TargetUserIDGTE(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldTargetUserID, v))
}

// TargetUserIDLT applies the LT predicate on the "target_user_id" field.
func TargetUserIDLT(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldTargetUserID, v))
}

// TargetUserIDLTE applies the LTE predicate on the "target_user_id" field.
func TargetUserIDLTE(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldTargetUserID, v))
}

// TargetUserIDIsNil applies the IsNil predicate on the "target_user_id" field.
func TargetUserIDIsNil() predicate.Report {
	return predicate.Report(sql.FieldIsNull(FieldTargetUserID))
}

// TargetUserIDNotNil applies the NotNil predicate on the "target_user_id" field.
func TargetUserIDNotNil() predicate.Report {
	return predicate.Report(sql.FieldNotNull(FieldTargetUserID))
}

// TargetPostIDEQ applies the EQ predicate on the "target_post_id" field.
func TargetPostIDEQ(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldTargetPostID, v))
}

// TargetPostIDNEQ applies the NEQ predicate on the "target_post_id" field.
func TargetPostIDNEQ(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldTargetPostID, v))
}

// TargetPostIDIn applies the In predicate on the "target_post_id" field.
func TargetPostIDIn(vs ...uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldTargetPostID, vs...))
}

// TargetPostIDNotIn applies the NotIn predicate on the "target_post_id" field.
func TargetPostIDNotIn(vs ...uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldTargetPostID, vs...))
}

// TargetPostIDGT applies the GT predicate on the "target_post_id" field.
func TargetPostIDGT(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldTargetPostID, v))
}

// TargetPostIDGTE applies the GTE predicate on the "target_post_id" field.
func TargetPostIDGTE(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldTargetPostID, v))
}

// TargetPostIDLT applies the LT predicate on the "target_post_id" field.
func TargetPostIDLT(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldTargetPostID, v))
}

// TargetPostIDLTE applies the LTE predicate on the "target_post_id" field.
func TargetPostIDLTE(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldTargetPostID, v))
}

// TargetPostIDIsNil applies the IsNil predicate on the "target_post_id" field.
func TargetPostIDIsNil() predicate.Report {
	return predicate.Report(sql.FieldIsNull(FieldTargetPostID))
}

// TargetPostIDNotNil applies the NotNil predicate on the "target_post_id" field.
func TargetPostIDNotNil() predicate.Report {
	return predicate.Report(sql.FieldNotNull(FieldTargetPostID))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Report {
	return predicate.Report(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Report {
	return predicate.Report(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Report {
	return predicate.Report(sql.FieldContainsFold(FieldType, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.Report {
	return predicate.Report(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.Report {
	return predicate.Report(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.Report {
	return predicate.Report(sql.FieldContainsFold(FieldReason, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Report {
	return predicate.Report(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Report {
	return predicate.Report(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Report {
	return predicate.Report(sql.FieldContainsFold(FieldStatus, v))
}

// ReviewNotesEQ applies the EQ predicate on the "review_notes" field.
func ReviewNotesEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldReviewNotes, v))
}

// ReviewNotesNEQ applies the NEQ predicate on the "review_notes" field.
func ReviewNotesNEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldReviewNotes, v))
}

// ReviewNotesIn applies the In predicate on the "review_notes" field.
func ReviewNotesIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldReviewNotes, vs...))
}

// ReviewNotesNotIn applies the NotIn predicate on the "review_notes" field.
func ReviewNotesNotIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldReviewNotes, vs...))
}

// ReviewNotesGT applies the GT predicate on the "review_notes" field.
func ReviewNotesGT(v string) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldReviewNotes, v))
}

// ReviewNotesGTE applies the GTE predicate on the "review_notes" field.
func ReviewNotesGTE(v string) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldReviewNotes, v))
}

// ReviewNotesLT applies the LT predicate on the "review_notes" field.
func ReviewNotesLT(v string) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldReviewNotes, v))
}

// ReviewNotesLTE applies the LTE predicate on the "review_notes" field.
func ReviewNotesLTE(v string) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldReviewNotes, v))
}

// ReviewNotesContains applies the Contains predicate on the "review_notes" field.
func ReviewNotesContains(v string) predicate.Report {
	return predicate.Report(sql.FieldContains(FieldReviewNotes, v))
}

// ReviewNotesHasPrefix applies the HasPrefix predicate on the "review_notes" field.
func ReviewNotesHasPrefix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasPrefix(FieldReviewNotes, v))
}

// ReviewNotesHasSuffix applies the HasSuffix predicate on the "review_notes" field.
func ReviewNotesHasSuffix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasSuffix(FieldReviewNotes, v))
}

// ReviewNotesEqualFold applies the EqualFold predicate on the "review_notes" field.
func ReviewNotesEqualFold(v string) predicate.Report {
	return predicate.Report(sql.FieldEqualFold(FieldReviewNotes, v))
}

// ReviewNotesContainsFold applies the ContainsFold predicate on the "review_notes" field.
func ReviewNotesContainsFold(v string) predicate.Report {
	return predicate.Report(sql.FieldContainsFold(FieldReviewNotes, v))
}

// ReviewedByEQ applies the EQ predicate on the "reviewed_by" field.
func ReviewedByEQ(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldReviewedBy, v))
}

// ReviewedByNEQ applies the NEQ predicate on the "reviewed_by" field.
func ReviewedByNEQ(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldReviewedBy, v))
}

// ReviewedByIn applies the In predicate on the "reviewed_by" field.
func ReviewedByIn(vs ...uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldReviewedBy, vs...))
}

// ReviewedByNotIn applies the NotIn predicate on the "reviewed_by" field.
func ReviewedByNotIn(vs ...uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldReviewedBy, vs...))
}

// ReviewedByGT applies the GT predicate on the "reviewed_by" field.
func ReviewedByGT(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldReviewedBy, v))
}

// ReviewedByGTE applies the GTE predicate on the "reviewed_by" field.
func ReviewedByGTE(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldReviewedBy, v))
}

// ReviewedByLT applies the LT predicate on the "reviewed_by" field.
func ReviewedByLT(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldReviewedBy, v))
}

// ReviewedByLTE applies the LTE predicate on the "reviewed_by" field.
func ReviewedByLTE(v uuid.UUID) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldReviewedBy, v))
}

// ReviewedByIsNil applies the IsNil predicate on the "reviewed_by" field.
func ReviewedByIsNil() predicate.Report {
	return predicate.Report(sql.FieldIsNull(FieldReviewedBy))
}

// ReviewedByNotNil applies the NotNil predicate on the "reviewed_by" field.
func ReviewedByNotNil() predicate.Report {
	return predicate.Report(sql.FieldNotNull(FieldReviewedBy))
}

// ReviewedAtEQ applies the EQ predicate on the "reviewed_at" field.
func ReviewedAtEQ(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldReviewedAt, v))
}

// ReviewedAtNEQ applies the NEQ predicate on the "reviewed_at" field.
func ReviewedAtNEQ(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldReviewedAt, v))
}

// ReviewedAtIn applies the In predicate on the "reviewed_at" field.
func ReviewedAtIn(vs ...time.Time) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldReviewedAt, vs...))
}

// ReviewedAtNotIn applies the NotIn predicate on the "reviewed_at" field.
func ReviewedAtNotIn(vs ...time.Time) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldReviewedAt, vs...))
}

// ReviewedAtGT applies the GT predicate on the "reviewed_at" field.
func ReviewedAtGT(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldReviewedAt, v))
}

// ReviewedAtGTE applies the GTE predicate on the "reviewed_at" field.
func ReviewedAtGTE(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldReviewedAt, v))
}

// ReviewedAtLT applies the LT predicate on the "reviewed_at" field.
func ReviewedAtLT(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldReviewedAt, v))
}

// ReviewedAtLTE applies the LTE predicate on the "reviewed_at" field.
func ReviewedAtLTE(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldReviewedAt, v))
}

// ReviewedAtIsNil applies the IsNil predicate on the "reviewed_at" field.
func ReviewedAtIsNil() predicate.Report {
	return predicate.Report(sql.FieldIsNull(FieldReviewedAt))
}

// ReviewedAtNotNil applies the NotNil predicate on the "reviewed_at" field.
func ReviewedAtNotNil() predicate.Report {
	return predicate.Report(sql.FieldNotNull(FieldReviewedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Report) predicate.Report {
	return predicate.Report(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Report) predicate.Report {
	return predicate.Report(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Report) predicate.Report {
	return predicate.Report(sql.NotPredicates(p))
}
